### ISSUE TITLE
Add SEO-friendly URLs

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#10]
Add SEO-friendly URLs.

References:
https://wordpress.org/support/topic/permanent-links-user-friendly?replies=2

Maybe:
https://wordpress.org/support/topic/facebook-like-button-problem-5?replies=13
Could be caused by wrong canoncial.

```
// Add Rewrite Rules
        /*
        add_rewrite_rule(
            '^([^/]*)/([^/]*)/([0-9]+)/?$',
            'index.php?pagename=$matches[1]&view=$matches[2]&id=$matches[3]',
            'top'
        );

        add_rewrite_rule(
            '^([^/]*)/([^/]*)/([0-9]+)/([0-9]+)/?$',
            'index.php?pagename=$matches[1]&view=$matches[2]&id=$matches[3]&part=$matches[4]',
            'top'
        );
        */

        // Add Rewrite Tags
        /*
        add_rewrite_tag('%view%', '([^/]*)');
        add_rewrite_tag('%id%', '([0-9]+)');
        add_rewrite_tag('%part%', '([0-9]+)');
        */
```

```
public function __construct($object) {
		self::$asgarosforum = $object;

        // Check if permalinks are enabled.
        if (get_option('permalink_structure')) {
            $usePermalinks = true;

            //add_action('init', array($this, 'addRewriteRules'));
        }
	}

    /*public static function addRewriteRules() {
        add_rewrite_rule(
            '^([^/]*)/forum/([0-9]+)/?$',
            'index.php?pagename=$matches[1]&view=forum&id=$matches[2]',
            'top'
        );
    }*/
```

**Comment by ironboys** [comment]
Whether will be in the following release to a chp? Well that instead of address/forums? view=thread&id=15#postid-25 was more clear forums/thread/nazvanie_temy address

**Comment by ironboys** [comment]
It will be good if the address of a subject is site.ru/forum/thread_title as in bbpress plug-in

**Comment by Asgaros** [comment]
For SEO-friendly URLs we need to create slugs for forums and topics. This can be done with the WordPress Core function sanitize_title(). While experimenting with this I am a little bit confused how this will work for non-latin characters, e.g. in chinese or cyrillic characters, because the function generates something like this:

`%e4%bd%a0%e5%a5%bd`
for 
`你好`

@Igor-Yworld As far as I know you are used to the cyrillic stuff. Is it common that slug-urls are looking like this or is there another way for this?

**Comment by Igor-Yworld** [comment]
@Asgaros Please watch this plugin https://wordpress.org/plugins/cyr3lat/
One of the two plug-ins that are used with the Cyrillic alphabet.

**Comment by Asgaros** [comment]
I opened the following ticket on WordPress Trac:
https://core.trac.wordpress.org/ticket/41680

Hopefully they implement a good solution for this so I can start to integrate this feature without ugly workarounds to make pretty URLs working on static front-pages.
