### ISSUE TITLE
Post title length

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#101]
I was wondering if you could add an option to change the maximum length of displayed post titles. Thank you!

**Comment by Asgaros** [comment]
Hello @jangevaare 

For which positions do you want to have the topic title-length configurable? I ask because it can appear in multiple areas where we have an different amount of space available (e.g. headline, last post-information in overview, etc).

**Comment by jangevaare** [comment]
Oh! I should've been more specific. I mean in the topics index within each forum. At full screen the topic titles only take up half of the available space on my site.
![screen shot 2016-12-08 at 2 36 02 pm](https://cloud.githubusercontent.com/assets/5422422/21024764/b0cab99a-bd53-11e6-8efa-e5ed418d2ac0.png)

**Comment by Asgaros** [comment]
Hello again, @jangevaare 

I changed the code a little bit so the titles of topics dont get shorten anymore. I think it is the best to show them in their full length (except in the small lastpost-area) so people always know what it is about.

Forum view:
![ewfewfew](https://cloud.githubusercontent.com/assets/12525671/21026870/d30582d4-bd8e-11e6-8ac3-f0432654a19f.PNG)

Topic view:
![fdsdfsfdsfds](https://cloud.githubusercontent.com/assets/12525671/21026869/d3038722-bd8e-11e6-872a-0c509dfe22c8.PNG)

Those changes will be included in the upcoming v1.3.0 release. :)
