### ISSUE TITLE
Crashes website with "HTTP ERROR 500" if active

### ISSUE THREAD

**Issue by armorproof** [Asgaros/asgaros-forum#104]
The Asgaros Forum plugin causes the website to crash with a "HTTP ERROR 500" error if activated. I am currently running Asgaros Forum version 1.3.0, Wordpress version 4.7, and the Vantage theme version 1.5.8. The issue began occurring when updates were installed to Wordpress and the Asgaros Forum plugin. Please help.

**Comment by Asgaros** [comment]
Hello @armorproof 

Which versions of MySQL and PHP are you using? Which other updates have you applied to your WordPress installation?

The only critical change I made with the last update is the creation of a fulltext index. Does your forum installation has a big amount of posts/topics because maybe this modification-query can take a while.

**Comment by armorproof** [comment]
Hey Asgaros,
The forum was small as the website is only a month old, 4 topics and 50 posts. I can't find where it shows the exact PHP version but I think it's 5 since the configuration files are in the directory /etc/php5/. The MySQL version is 5.5.53. I'm unsure exactly which other updates were applied to Wordpress, I'm assuming only updating Wordpress itself to 4.7, as it was a client that updated it. Any ideas?

**Comment by Asgaros** [comment]
@armorproof 

Have you tried to temporary disable other WordPress plugins you are using? Because maybe there is some compatibility problem with one of them which we can try to find and fix.

**Comment by armorproof** [comment]
Hey Asgaros,
It looks like it was being caused by another plugin named User Registration Aide by Brian Novotny, V1.5.3.4. I was able to get them both working by activating the Asgaros Forum first but I believe it may be a temporary fix. Any ideas why this might have happened so I can see about tackling the issue on my side?

**Comment by Asgaros** [comment]
Hello @armorproof 

I am happy to hear that it is working now again. I tested the User Registration Aide plugin on an test-installation and for me it is working fine - so its a little bit hard for me to reproduce the error. I think it could be possible that this plugin is not fully compatible with WordPress 4.7 yet but I hope that the error is gone.
