### ISSUE TITLE
A common question

### ISSUE THREAD

**Issue by Igor-Yworld** [Asgaros/asgaros-forum#106]
Hi Thomas!
Many questions from users, etc.
You do not mind, we have created support site for our users?
Integration with the plugin, add-ons ...

**Comment by Asgaros** [comment]
Hello @Igor-Yworld 

I already planned to create a Asgaros Forum-website in the future since a long time. Sadly I am very busy recently thats why I still use the WordPress support forums at the moment. I will give my best to do this next year.

**Comment by Igor-Yworld** [comment]
Thank you!
We made for the site of technical support of the Russian Federation.
Do you mind?
[http://af.yworld.ru/](url)

**Comment by Igor-Yworld** [comment]
@Asgaros Thank you for the great plugin!

**Comment by Asgaros** [comment]
This is looking very nice. Especially the modifications you made to it. I like the statistics-part as well and plan to add it in one of the next versions soon. :)

**Comment by Asgaros** [comment]
By the way: If there are some modifications you made to the forum which you want to see in the core-plugin, you can make a merge-request here in GitHub. I am open for any suggestions. :)

**Comment by Igor-Yworld** [comment]
Ок :)

**Comment by Asgaros** [comment]
@Igor-Yworld 

Which syntax-highlighter plugin are you using for your forum? Do you had to make some modifications to the forum software to make it work? I mean this one:
http://af.yworld.ru/forum/?view=thread&id=22&part=1#postid-49

**Comment by Igor-Yworld** [comment]
@Asgaros Hi
Enlighter - Customizable Syntax Highlighter https://wordpress.org/plugins/enlighter/
Without changes. In the plugin settings, turn on the frontend

**Comment by Asgaros** [comment]
Thank you! :)
