### ISSUE TITLE
[shortcode] for specific forum

### ISSUE THREAD

**Issue by cocoholo** [Asgaros/asgaros-forum#108]
would be awesome if each forum would have its own [shortcode] so i can just paste on on pages relevant to what my visitors are viewing.

also a [shortcode] i can paste in the widgets section showing recent posts of a specific forum

**Comment by Asgaros** [comment]
Hello @cocoholo 

This is already at my todo-list. See this ticket for more information:
https://github.com/Asgaros/asgaros-forum/issues/47
