### ISSUE TITLE
Thread/forum subscription summaries

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#112]
Hello! The forum is working very well for my homebrewing club, thanks for all of your work on it.

Some members are getting unexpected results from thread and forum subscriptions, i.e. they will receive subscription emails when they don't believe they should.

I wonder if it would help if there was a page to view all of a member's subscribed forums and topics - would help us narrow down the issue perhaps!

Cheers.

**Comment by Asgaros** [comment]
Hello @jangevaare 

I will add this functionality when I implement the Profile functinality. Maybe your users accidentally checked the "Notify about new topics" option in their user profile so they got notifications about any new topic?

**Comment by jangevaare** [comment]
Thanks, cheers!

**Comment by Asgaros** [comment]
Hello @jangevaare 

did you have a look if those options were activated because I got a similar error-report about this here and sadly I couldnt reproduce the error yet:
https://www.asgaros.de/support/?view=thread&id=30

**Comment by jangevaare** [comment]
Just checked, the user that complained about the issue does not have that option activated. 

<img width="855" alt="screen shot 2017-01-16 at 1 35 50 pm" src="https://cloud.githubusercontent.com/assets/5422422/21995044/cad223d0-dbf0-11e6-95ea-4cc0d45028ef.png">

**Comment by Asgaros** [comment]
Got it! Fixed it! This was a little bit hard to find because I just forgot one important line of code. :(

Sorry for the circumstances!
