### ISSUE TITLE
Reply on page

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#113]
Hello.

The new reply on page is very nice. When a user clicks the reply button on the bottom of the page though, it's not immediately obvious how they can write that reply. Perhaps if the reply button at the button also caused a page up, that'd work well!

**Comment by Asgaros** [comment]
Hello @jangevaare 

When I press the reply-buttons, the page is automatically scrolling up and focusing the editor or subject line for me. In which browser did you test it?

**Comment by jangevaare** [comment]
This is in Safari 10.0.2.

It could be related to my theme possibly? I've had issues before with it (e.g. stickies don't work with my theme).

**Comment by Asgaros** [comment]
Can you tell me again the name of your theme you are using? Or was it one you developed by your own? I can try to have a look at it.

**Comment by jangevaare** [comment]
It is called eighteen tags, version 1.0.8

**Comment by Asgaros** [comment]
I installed your theme again and it is still working for me. Maybe it is a problem with Safari. Sadly I cant test it because I have no machine with it. :( Does this only happens for new posts or also for topics?

But there are also some good news: Finally I could fix your sticky/unsticky/open/close problem: https://github.com/Asgaros/asgaros-forum/commit/0597fe9550998a92551f34c51fcf2ad871592ad5

**Comment by jangevaare** [comment]
Thanks for fixing that!

The "new topic" button on the bottom of the page causes the browser to go to the top of the page correctly.

I should clarify, that using the reply button on the bottom of the page causes the browser to page up *slightly*, but not all the way to the top. 

I just tried in firefox, and a similar thing happens. The browser does not page up to the top of the screen as it should, it does page up part way though. I'm testing this on topics with many replies if it helps you recreate the issue!

**Comment by Asgaros** [comment]
@jangevaare I just made some commits to the dev-version which should fix it. Can you please test it? :)

**Comment by jangevaare** [comment]
Works perfectly!

**Comment by Asgaros** [comment]
Thanks for the feedback! I will include it in the next release and hope that I can also find and include a fix for the subscription-bug.
