### ISSUE TITLE
Feature request: page links in topic index

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#114]
Hello again,
Often times I will click on a topic, only to have to immediately click page 2 or 3 when it loads so I can get to the most recent replies. Do you think you could add the page links within each topic right in the topics index? I think that'd be very useful! Cheers!

**Comment by Asgaros** [comment]
Hello @jangevaare 

Basically you can also click at the time in the last-post area. It also brings you to the last page.

But yes, I will think about to add page-links there as well. :)
