### ISSUE TITLE
Shortcodes in Signatur

### ISSUE THREAD

**Issue by SiSchae** [Asgaros/asgaros-forum#115]
Gibt es eine Möglichkeit in der Signature der User Shortcodes zu Nutzen. Würde gerne die Möglichkeit haben, dass der User seine in Wordpress eingegebenen Kontaktinformationen in seine Signatur einbetten kann. Die Shortcodes dafür habe ich schon erstellt. Die Signatur wertet diese aber nicht aus, sondern schreibt sie als [Shortcode].

**Comment by Asgaros** [comment]
Hallo, das ist momentan leider nicht möglich und möchte ich standardmäßig ehrlich gesagt auch nicht zulassen - das selbe gilt für HTML. Der Grund dafür ist, dass die Signatur sonst für allerlei Unsinn ausgenutzt werden kann. So könnten zum Beispiel Videos oder größere Bilder eingebettet werden. Eine Filtermöglichkeit wäre somit notwendig.

Was ich dir anbieten kann ist das hinzufügen eines neuen Hooks in den Signatur-Bereich. Über diesen könntest du dich dann über eine eigene Funktion in die Signatur reinhängen und automatisch einen Text basierend auf den gewünschten Daten generieren.

**Comment by SiSchae** [comment]
Ich hab in die "includes/views/post-element.php" mal testweise ein "do_shortcode" in den Signatur-Bereich eingefügt. Habe es aber auch wieder rausgenommen, da wie du oben geschrieben hast, man die Signatur dadurch sehr Aufblasen kann. 

Danke dir trotzdem für deine Anwort. Das Forum ist echt der Hammer!
