### ISSUE TITLE
RSS-Feeds

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#116]
Implement RSS-Feeds.

References:
https://wordpress.org/support/topic/rss-feed-generator-needed-must-have/
https://wordpress.org/support/topic/rss-feed-164/

Possible implementation:
https://wordpress.org/support/topic/temporary-but-working-rss-2-0-forum-topic-newsfeed/

**Comment by guideloom** [comment]
Any chance this will be implemented in the next (or soon to be) release? I have a few folks really wanting this.

**Comment by Asgaros** [comment]
Hello @guideloom 

Yes. Currently I am working on post-history view for users and I plan to add rss-feeds after I completed it.

**Comment by Asgaros** [comment]
@guideloom 
FYI: RSS feeds for topics and forums will be available in the upcoming v1.9.7 update which I plan to release in the beginning of September.
