### ISSUE TITLE
Add User Groups Functionality

### ISSUE THREAD

**Issue by duckhawk** [Asgaros/asgaros-forum#117]
Is it possible to add asgaros-forum-user-groups plugin functional into the core?

https://github.com/Asgaros/asgaros-forum-user-groups

Now, as I see, the hooks, used by this plugin, removed from forum.

**Comment by Asgaros** [comment]
Hello @duckhawk 

Yes, I plan to add this with the next version 1.5 in the mid/end of April.

**Comment by Asgaros** [comment]
Hello @duckhawk 

You can use usergroups again with the latest test-version of the plugin in combination with the User Groups plugin from Katz Web Services (https://wordpress.org/plugins/user-groups/).

I will include that library into core in a few days as well.

**Comment by Asgaros** [comment]
Good news: I just finished the implementation of the user groups-functionality into the forum. You can now create your own user groups inside the forum-settings, add users to them and restrict the access to categories for certain user groups without the need of installing any other third-party plugin.

The user groups functionality will be included in the upcoming v1.5 release which I plan to release in the coming five days.
