### ISSUE TITLE
Request: preserve paragraph structure in quotes

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#120]
Hello! I was wondering if you could make it such that paragraph/message format was displayed correctly when quoted. It seems to me that the line breaks are being dropped when quoted. Cheers, and thanks for your continued development of this excellent software.

**Comment by Asgaros** [comment]
Hello,
this is working fine for me. Do you have a link to your site so I can check the CSS? I think that some CSS rules of your theme are responsible for this.

**Comment by jangevaare** [comment]
Oh thank you. The website address is http://truegrist.ca

Let me know if anything else is required.

**Comment by Asgaros** [comment]
Can you post me a link to a topic where I can see this problem in action?

**Comment by jangevaare** [comment]
Yes, check out posts 12 and 13 in this thread

http://truegrist.ca/forum/?view=thread&id=450

**Comment by Asgaros** [comment]
Hello again,

Paragraphs are now saved correctly inside of quotes in the dev-version.

I am very sorry that I cant fix this on existing quotes. :(
