### ISSUE TITLE
Importing from bbPress

### ISSUE THREAD

**Issue by uncovery** [Asgaros/asgaros-forum#124]
Hi,

I switched from bbPress to Asgaros. I wanted to import my posts from bbPress to Asgaros and I am running into the following situation:

I wrote PHP code to copy the data over into a specific top-level category. It works basically fine but after the import, the frontpage of the forum takes forever to load. It seems that the software is running some process across all posts (index?) 

Since I am importing 8k posts, I was wondering if there was anything I could know in order to reduce this behavior.

thanks!

**Comment by Asgaros** [comment]
Hello @uncovery 

Are you sure that you imported everything correctly into the three custom tables of the forum? Basically the plugin should work without problems when using the **latest** version of the forum - even when there are thousands of posts.

**Comment by uncovery** [comment]
Yeah I figured that the issue is that the unread count update is what takes forever. once I disabled that all was fine. I then re-enabled it again, but still having like 8k posts, even the "mark all as read" takes forever.

**Comment by uncovery** [comment]
By the way if you are interested in creating a BBPress import function, here is my code. Nothing fancy since I used it only once, but it works: https://pastebin.com/LWJaWJED

The umc_mysql_... are just abstraction layers for Mysql, see here: https://github.com/uncovery/uncovery_mysql 

I also first created a category in your forum software and took the ID, then moved things around between the forums and categories manually in phpMyAdmin later.

**Comment by uncovery** [comment]
you would need to program PHP for this one much more than anything else.

**Comment by Yeye64** [comment]
Sure, my DB is different than minecraft :-)
but i don't understand what i must doing with "uncovery_mysql.inc.php" and  the pastebin code.

When i try "uncovery_mysql.inc.php", i have the message : `ERROR checking failed, install XMPP_ERROR!`

Thanks

**Comment by Yeye64** [comment]
Can you explain me in detail ?

**Comment by uncovery** [comment]
I updated the uncovery_mysql, should work now.

**Comment by Yeye64** [comment]
Hi, thanks but i have white page with correct db, table...

Nothing is happening

**Comment by uncovery** [comment]
Sorry, but I never expected this to be for someone who does not know basic PHP.

You need to put a 

`umc_wp_forum_import();`

on the top of the code to call the actual function.

**Comment by Yeye64** [comment]
Ok, i'm really a noob... i don't undertstand anything... i will stay on bbpress :(
Very thanks for your support.

**Comment by Yeye64** [comment]
i try to understand a few ... :)

On a retry test with correct db, table... i have this error: `Fatal error: Uncaught Error: Call to a member function prepare() on null in /data/web/XXX/www/uncovery_mysql.inc.php:239 Stack trace: #0 /data/web/XXX/www/uncovery_mysql.inc.php(19): umc_mysql_fetch_all('SELECT post_tit...') #1 /data/web/XXX/www/uncovery_mysql.inc.php(88): umc_wp_forum_import() #2 {main} thrown in /data/web/XXX/www/uncovery_mysql.inc.php on line 239`

**Comment by Yeye64** [comment]
XXX is my web site not really XXX

**Comment by uncovery** [comment]
Since you changed the line numbers I cannot help you here

**Comment by Yeye64** [comment]
I have just mix the two files... in order to call umc_wp_forum_import(); function.

`<?php

/**
 * Import the forum bbpress into the new forum
 *
 *
 */
function umc_wp_forum_import() {
    // get all the current posts
    $DB = 'XXXXX';
    $table = 'YYY_posts';
    $forum_prefix = 'YYY_forum';
    $import_category = 129;
   
    // forums
    $sql_forum = "SELECT post_title, post_author, ID, post_date, post_content, post_name FROM `$DB`.`$table` "
        . "WHERE post_type='forum' AND post_status='publish';";
 
    $F = umc_mysql_fetch_all($sql_forum);
    foreach ($F as $f) {
        $check_duplicates = "SELECT * FROM `{$forum_prefix}_forums` WHERE parent_id=$import_category AND slug='{$f['post_name']}'";
        $C = umc_mysql_fetch_all($check_duplicates);
        if (count($C) > 0) {
            continue;
        }
        echo $f['post_title'] . "<br>";
       
        // insert new forum
        $ins_forum = "INSERT INTO `{$forum_prefix}_forums`(`name`, `parent_id`, `parent_forum`, `description`, `sort`, `closed`, `slug`) "
            . "VALUES ('{$f['post_title']}', $import_category, 0, '{$f['post_content']}', 99 , 1 ,'{$f['post_name']}')";
        umc_mysql_execute_query($ins_forum);
        $ins_forum_id = umc_mysql_insert_id();
        umc_wp_forum_import_topics($f['ID'], $ins_forum_id);
        break;
    }
    echo "done!";
}
 
function umc_wp_forum_import_topics($source_id, $target_id) {
	$DB = 'XXXXX';
    $table = 'YYY_posts';
    $forum_prefix = 'YYY_forum';';
   
    $sql_topics = "SELECT post_title, post_author, ID, post_date, post_content, post_name FROM `$DB`.`$table` "
        . "WHERE post_type='topic' AND post_status='publish' AND post_parent=$source_id;";
    $T = umc_mysql_fetch_all($sql_topics);
    foreach ($T as $t) {
        // insert topic
        $title = umc_mysql_real_escape_string($t['post_title']);
        $ins_topic = "INSERT INTO `{$forum_prefix}_topics`(`parent_id`, `views`, `name`, `status`) VALUES "
            . "($target_id, 0,$title,'normal_open')";
        umc_mysql_execute_query($ins_topic);
        $ins_topic_id = umc_mysql_insert_id();  
       
        // insert the text of the main post
        $content = umc_mysql_real_escape_string($t['post_content']);
        $ins_topic_text = "INSERT INTO `{$forum_prefix}_posts`(`text`, `parent_id`, `date`, `author_id`, `uploads`) VALUES "
            . "($content, $ins_topic_id,'{$t['post_date']}',{$t['post_author']}, 'a:0:{}')";
        umc_mysql_execute_query($ins_topic_text);
       
        // insert the replies
        umc_wp_forum_import_replies($t['ID'], $ins_topic_id);        
    }
}
 
function umc_wp_forum_import_replies($source_id, $target_id) {
    $DB = 'XXXXX';
	$table = 'YYY_posts';
	$forum_prefix = 'YYY_forum';
   
    $sql_replies = "SELECT post_title, post_author, ID, post_date, post_content, post_name FROM `$DB`.`$table` "
         . "WHERE post_type='reply' AND post_status='publish' AND post_parent=$source_id;";
    $R = umc_mysql_fetch_all($sql_replies);
    foreach ($R as $r) {
        // insert the text of the main post
        $content = umc_mysql_real_escape_string($r['post_content']);
        $ins_reply = "INSERT INTO `{$forum_prefix}_posts`(`text`, `parent_id`, `date`, `author_id`, `uploads`) VALUES "
            . "($content, $target_id,'{$r['post_date']}',{$r['post_author']}, 'a:0:{}')";
        umc_mysql_execute_query($ins_reply);
    }
}


/**
 * PDO abstraction
 *
 */
 umc_wp_forum_import();
global $UNC_DB;

// configure your database here
$default_config=array(
    'database'  => 'XXXXX',
    'username'  => 'AZERTY',
    'server'  => 'mysql.ZZZZ.fr',
    'password'  => 'PASSWORD',
);
// let's set the values in the global variable
foreach ($default_config as $type  => $value) {
    if (!isset($UNC_DB[$type])) {
        $UNC_DB[$type]=$value;
    }
}
// this is custom error reporting
// see https://github.com/uncovery/xmpp_error for more info
// if not available, will be ignored
$UNC_DB['XMPP_ERROR'] = true;
if (!function_exists('XMPP_ERROR_trace')) {
    $UNC_DB['XMPP_ERROR'] = false;
}
// make a connection to the database.
$UNC_DB['link']=new PDO("mysql:host={$UNC_DB['server']};dbname={$UNC_DB['database']}", $UNC_DB['username'],$UNC_DB['password']);
$UNC_DB['link']->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_WARNING);
/**
 * Replacement for mysql_query
 * returns result. includes error notification
 *
 * can close the query if needed, otherwise returns result
 *
 * @global PDO $UMC_DB
 * @param string $sql
 * @param boolean $close
 * @return type
 */
function umc_mysql_query($sql, $close=false) {
    global $UNC_DB;
    if ($UNC_DB['XMPP_ERROR']) {XMPP_ERROR_trace(__FUNCTION__, func_get_args());}
    $rst=$UNC_DB['link']->query($sql);
    $error=$UNC_DB['link']->errorInfo();
    if (!is_null($error[2]) && $UNC_DB['XMPP_ERROR']) {
        XMPP_ERROR_trigger("MySQL Query Error: '$sql' : " . $error[2]);
        return false;
    } if (!is_null($error[2])) {
        error_log("MySQL Query Error: '$sql' : " . $error[2]);
        return false;
    } else if ($close) {
        $rst->closeCursor();
        return true;
    } else {
        return $rst;
    }
}
/**
 * Replacement for mysql_query
 * specific for DELETE, UPDATE and INSERT queries. returns affected rows
 *
 * can close the query if needed, otherwise returns result
 *
 * @global PDO $UMC_DB
 * @param string $sql
 * @param boolean $close
 * @return type
 */
function umc_mysql_execute_query($sql) {
    global $UNC_DB;
    if ($UNC_DB['XMPP_ERROR']) {XMPP_ERROR_trace(__FUNCTION__, func_get_args());}
    $obj=$UNC_DB['link']->prepare($sql);
    $obj->execute();
    $error=$obj->errorInfo();
    if (!is_null($error[2]) && $UNC_DB['XMPP_ERROR']) {
        XMPP_ERROR_trigger("MySQL Query Error: '$sql' : " . $error[2]);
        return false;
    } else if (!is_null($error[2]) ) {
        error_log("MySQL Query Error: '$sql' : " . $error[2]);
        return false;
    } else {
        $count=$obj->rowCount();
        return $count;
    }
}
/**
 * Replacement for mysql_affected_rows
 * Returns count. Optionally closes the recordset
 *
 * @param recordset $rst
 * @param boolean $close
 * @return int
 */
function umc_mysql_affected_rows($rst, $close=false) {
    $rowCount=$rst->fetchColumn();
    if ($close) {
        $rst->closeCursor();
    }
    return $rowCount;
}
/**
 * Replacement for mysql_insert_id
 *
 * @global PDO $UMC_DB
 * @return type integer
 */
function umc_mysql_insert_id() {
    global $UNC_DB;
    return $UNC_DB['link']->lastInsertId();
}
/**
 * Replacement for mysql_fetch_array (MYSQL_ASSOC)
 * Returns one line of associative arrays
 *
 * @param type $rst
 * @return type
 */
function umc_mysql_fetch_array($rst) {
    global $UNC_DB;
    if ($UNC_DB['XMPP_ERROR']) {XMPP_ERROR_trace(__FUNCTION__, func_get_args());}
    if (!$rst && $UNC_DB['XMPP_ERROR']) {
        XMPP_ERROR_trigger("tried fetch_array on erroneous recordset");
        return false;
    } else if (!$rst) {
        error_log("tried fetch_array on erroneous recordset");
        return false;
    }
    $row=$rst->fetch(PDO::FETCH_ASSOC);
    return $row;
}
/**
 * Replacement of mysql_free_result
 *
 * @param type $rst
 */
function umc_mysql_free_result($rst) {
    $rst->closeCursor();
}
/**
 * Replacement of mysql_real_escape_string
 * ATTENTION: This also puts quotes around the value
 *
 * @global PDO $UMC_DB
 * @param type $value
 * @return type
 */
function umc_mysql_real_escape_string($value) {
    global $UNC_DB;
    return $UNC_DB['link']->quote($value);
}
function umc_mysql_fetch_all($sql) {
    global $UNC_DB;
    if ($UNC_DB['XMPP_ERROR']) {XMPP_ERROR_trace(__FUNCTION__, func_get_args());}
    $stmt=$UNC_DB['link']->prepare($sql);
    if (!$stmt && $UNC_DB['XMPP_ERROR']) {
        $error=$UNC_DB['link']->errorInfo();
        XMPP_ERROR_trigger($error);
        return false;
    } else if (!$stmt) {
        error_log($UNC_DB['link']->errorInfo());
        return false;
    } else {
        $stmt->execute();
    }
    $result=$stmt->fetchAll(PDO::FETCH_ASSOC);
    return $result;
}`



I have replace db, password, username, server name .... :)

**Comment by uncovery** [comment]
You will have to make at least some effort to enable me to help you. How am I supposed to get the line number from the above? I won't count them, right? Please paste this to a Gist (https://gist.github.com/) or to a pastebin of your choice so I can get them. Also, I assume you are running PHP 7+?

**Comment by uncovery** [comment]
ok it means that the database link was not properly created.
So please check the username/password/database setting in line 93. Also check your logfile if there are any other errors/notices visible

**Comment by Yeye64** [comment]
username/password/database are good, and no errors in acces log, php log and error log. :-/

**Comment by uncovery** [comment]
Change lines 112 / 113 from

```
$UNC_DB['link']=new PDO("mysql:host={$UNC_DB['server']};dbname={$UNC_DB['database']}", $UNC_DB['username'],$UNC_DB['password']);
$UNC_DB['link']->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_WARNING);
```

to 

```
$UNC_DB['link']=new PDO("mysql:host={$UNC_DB['server']};dbname={$UNC_DB['database']}", $UNC_DB['username'],$UNC_DB['password']);
var_dump($UNC_DB['link']);
$UNC_DB['link']->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_WARNING);
var_dump($UNC_DB['link']);
```
and tell me what the output is.

**Comment by Yeye64** [comment]
I have this error : 
`Fatal error: Uncaught Error: Call to a member function prepare() on null in /data/web/NL-7401/meeplejuice/www/uncovery_mysql.inc.php:241 Stack trace: #0 /data/web/NL-7401/meeplejuice/www/uncovery_mysql.inc.php(19): umc_mysql_fetch_all('SELECT post_tit...') #1 /data/web/NL-7401/meeplejuice/www/uncovery_mysql.inc.php(88): umc_wp_forum_import() #2 {main} thrown in /data/web/NL-7401/meeplejuice/www/uncovery_mysql.inc.php on line 241`

**Comment by Yeye64** [comment]
i modify a few my php, see it to this pastbin : https://pastebin.com/i4YEDiHP

now i have this  message : 
`object(PDO)#1 (0) { } object(PDO)#1 (0) { }
Warning: PDOStatement::execute(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'post_title' in 'field list' in /data/web/zzz/www/uncovery_mysql.inc.php on line 251
done!`

but no export yet.

**Comment by Yeye64** [comment]
In YYY_posts, i have the colums post_title

**Comment by Yeye64** [comment]
What i must doing ?

**Comment by Yeye64** [comment]
So, your method doesn't work for me...

I try another way wich works (inspired by [this post bbpress to phpbb](https://www.phpbb.com/community/viewtopic.php?t=2439331))
As you, first created a category in your Asgaros forum and took the ID.

`

/* Clear tables and reset IDs */
TRUNCATE TABLE wp_forum_forums;
TRUNCATE TABLE wp_forum_topics;
TRUNCATE TABLE wp_forum_posts;

/* Transfer forums */
INSERT INTO wp_forum_forums (
	id,
	name,
	description,
	parent_id,
	slug
) SELECT
    f.id /* Forum ID */,
    f.post_title /* name */,
    f.post_content /* Description */,
	137 /* ID of your category that you have create */,
	f.post_name /*slug */
FROM
    wp_posts AS f
WHERE
    f.post_type = 'forum';



/* Transfer the topics */
INSERT INTO
    wp_forum_topics (
        id,
		name,
		slug,
        parent_id
    )
SELECT
    t.id /* Topic ID */,
	t.post_title /* Topic title */,
	t.post_name /* slug */,
	t.post_parent /* Forum ID */
FROM
    wp_posts AS t
WHERE
    t.post_type = 'topic';

/* Transfer replies */
INSERT INTO
    wp_forum_posts (
        id,
        text,
        parent_id,
        forum_id,
        date,
        author_id
    )
SELECT
    p.id /* ID */,
    p.post_content /* text */,
	t.id /* Topic ID */,
    f.id /* Forum ID */,
	p.post_date /* Date */,
	p.post_author /* author_id */  
 
FROM
    wp_posts AS p
INNER JOIN
    wp_users AS u ON p.post_author = u.id
INNER JOIN
    wp_posts AS t ON p.post_parent = t.id OR p.id = t.id
INNER JOIN
    wp_posts AS f ON t.post_parent = f.id
WHERE
    p.post_type in ('reply','topic')
AND
    t.post_type = 'topic'
AND
    f.post_type = 'forum';
`
