### ISSUE TITLE
Moving Forums

### ISSUE THREAD

**Issue by uncovery** [Asgaros/asgaros-forum#125]
It would be great to have an admin tool to move topics from one Category to another.

**Comment by Asgaros** [comment]
Hello,

you can already move topics from the frontend from one forum to another. Of course I can try to improve this in future release so that bulk-moving could be also possible.

**Comment by uncovery** [comment]
I got confused with this. First I could not find the function, then I saw that there is some code relating to moving things. So I thought I just overlooked something. Then I realized that it's only for moving individual posts. 

What is missing from my point of view is any tool to reorganize the forum, be it moving forums to another category or bulk-moving (i.e. all) topics to another forum. 

would be great to have.

**Comment by uncovery** [comment]
By the way if you are interested in creating a BBPress import function, here is my code. Nothing fancy since I used it only once, but it works: https://pastebin.com/LWJaWJED

The umc_mysql_... are just abstraction layers for Mysql, see here: https://github.com/uncovery/uncovery_mysql

**Comment by Asgaros** [comment]
I finally added it and it will be available with the upcoming v1.8 release.
