### ISSUE TITLE
Cancel button when replying to a forum post

### ISSUE THREAD

**Issue by artypea** [Asgaros/asgaros-forum#129]
If you try to cancel a reply to a forum post, the Cancel button doesn’t appear to do anything

**Comment by Asgaros** [comment]
Hello @artypea 

- In which browser does the error occur?
- Do you have JavaScript enabled?
- Can you please clear your browser cache?
- Do you use the latest version of the plugin?

If you are using Google Chrome, please try the following:
- Press CTRL + SHIFT + J
- Go to "Console"
- Check if there are some JavaScript errors when you are using your website/forum/cancel-button

I tested it with Google Chrome and everything is working fine so far.
