### ISSUE TITLE
Search Widget

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#132]
I'd like to move the search form to a side bar, it would be great if it were available as a widget!

Cheers,
Justin

**Comment by Asgaros** [comment]
I just implemented a search widget. It will be available with the upcoming v1.7.0 release.

![search widget](https://user-images.githubusercontent.com/12525671/34837680-e0924dae-f6fb-11e7-8309-eb4c993f0881.PNG)
