### ISSUE TITLE
Signature ...

### ISSUE THREAD

**Issue by Elwoodb** [Asgaros/asgaros-forum#133]
Hello, congratulations for working on this forum.
I am disappointed by the fact that I can not add an image to the signature.
I understand your argument that it distracts the members.
but would not it make sense to let each administrator to decide?
Providing the possibility of putting an image in signature is usual in a large majority of forums ...
If it is not be important to you but it can be for the other;)
In the hope that you will come back on your decision.
Respectfully,

Elwoodb.
Sorry for my English I use google translation

**Comment by Asgaros** [comment]
See the following answer-post for more information:
https://www.asgaros.de/support/?view=thread&id=158&part=1#postid-772
