### ISSUE TITLE
Feature request: Post histories by user

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#139]
I know this is a feature of many other forum software, where you can find a user's post history by going to their profile.

**Comment by jangevaare** [comment]
To add, if such a history were to be generated, it would be useful if the post counter under a user's name linked to it.

**Comment by yunluo** [comment]
+1

**Comment by MeryK** [comment]
+1!!!! Waiting!!!!

**Comment by Asgaros** [comment]
Hello everyone. I just started working on it and this enhancement will be available with the upcoming version 1.9.3 which will come somewhere around June/July.
