### ISSUE TITLE
Remove subscriptions when a user loses access to a hidden forum

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#140]
Hello,
I have a forum on my site which is only visible to a group of users (club organizers). The club organizers change periodically. When somebody has access to this forum, and subscribed to topics and to the forum itself, these still show up in their subscription list (in my case http://truegrist.ca/forum/?view=subscriptions) after their access has been removed. I'm unsure if they still get subscription emails. I understand it's a tricky thing, but it would be great if only subscriptions that a user had permissions for were visible. Thanks!

**Comment by Asgaros** [comment]
Thanks for the info. I will definitely fix this with the next update. Sadly I am on an Asia Trip until end of October so I am not sure if I can release a new version before I come back.

**Comment by Asgaros** [comment]
I just had a short look and I think this requires a lot of refactoring which allows me to implement some checking/clean-up logic in a good and performant way. So this will definitely come a little bit later after my trip. In the meantime I will release v1.6 in the next few hours which fixes a couple of other bugs and brings some enhancements. Sorry to let you wait.

**Comment by Asgaros** [comment]
Sorry for the delay, but its finally fixed. Users got no notifications when they had no access to it but the topics still appeared on the list, yes. I do some further checks now in the code to remove those items from the list when an user has no access to a specific category based on access/usergroup settings.

The fix will be included in the next update.
