### ISSUE TITLE
Truncate long quotes

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#145]
Truncate long quotes

**Comment by springers54** [comment]
@Asgaros : funktioniert bei mir überhaupt nicht so mit dem Zitieren, wie ich es mir vorstelle.
Wenn ich in einem Post einen Absatz markiere und auf Zitat gehe, dann bekomme ich den kompletten Beitrag als Zitat und muss dann alles von Hand rauslöschen, was ich nicht haben wollte. Was mache ich falsch?

**Comment by Asgaros** [comment]
@springers54 

Eine Zitierung auf Basis des markierten Textes ist momentan nicht moeglich. Das in diesem Ticket geloeste Problem hat sich auf die angezeigten langen Zitate innerhalb von Beitraegen bezogen. Diese werden nun gekuerzt dargestellt, wenn ein Zitat eine entsprechende Mindestlaenge besitzt.

Bzgl zitieren auf Basis der Markierung: Ich weiss gar nicht, ob das ueberhaupt vernuenftig implementierbar waere. Gerade in Bezug mit etwaigem HTML, eingebundenen Bildern, Videos, der Handhabung von Markierungen ausserhalb des Beitrages, etc. Vielleicht schaue ich mir das mal an, wenn ich die ganzen anderen offenen Baustellen abgefertigt habe, aber versprechen kann ich da momentan leider noch nichts.
