### ISSUE TITLE
Custom CSS for textaera (iframe)

### ISSUE THREAD

**Issue by joergsteinhauer** [Asgaros/asgaros-forum#147]
Hello,

is there a way to add custom CSS to the textarea which is placed inside of the "message" iframe?

![2017-12-04 14_26_50-zen-reiki-internetschule_ forum - meinungen austauschen und lernen _zen-reiki](https://user-images.githubusercontent.com/1843754/33555165-9d4c237c-d8ff-11e7-83b9-0f9a1e4e636d.png)

I need a different font inside the textarea, but I don't see any way to implement custom CSS. If I look inside the DOM, I don't even see any CSS files or other head stuff.

![2017-12-04 14_27_32-developer tools - https___zen-reiki de_forum__view forum id 9](https://user-images.githubusercontent.com/1843754/33555169-9ffe672e-d8ff-11e7-9ae7-4c1739e26ce5.png)

Thanks

**Comment by Asgaros** [comment]
Hello @joergsteinhauer 

For the forum plugin I am using the default WordPress editor which I just implement into the forum extension with a simple function call to wp_editor(). This means, that all the styling and behavior is coming from the default WordPress core and not from extension.

But you can change those stylings via your WordPress theme. For example create a new file called **editor.css** in your themes directory which contains the following content:

```
* {
    font-family: sans-serif;
}
```

Now add the following PHP code to your themes **functions.php** file to include that css in the editor:

```
// Add a custom stylesheet to the TinyMCE editor.
function addEditorCSS($mce_css) {
	if (!empty($mce_css)) {
		$mce_css .= ',';
	}

	$mce_css .= get_template_directory_uri().'/editor.css';

	return $mce_css;
}

add_filter('mce_css', 'addEditorCSS');
```

Thats it! Now - after clearing the cache - your editors font should be sans-serif. :)

**Comment by joergsteinhauer** [comment]
thank you :). I did everything you said, but... it still doesn't work. there is no link-ta to the css file in the head-section inside of the iframe. 

as you can see here, there is only a meta-tag in the head. 

![2017-12-06 12_30_06-developer tools - https___zen-reiki de_forum__view forum id 9](https://user-images.githubusercontent.com/1843754/33659763-b00abe78-da81-11e7-8870-d816fa302f11.png)

**Comment by Asgaros** [comment]
The code should add the new css-file to the head-area of your main-document, not inside the iframe. I tested it with the default and custom templates which I am using and its working fine. Have you cleared your browser cache? If it has no impact at all, it could be possible that your theme is already overwriting editor-styles. In this case you have to find and adjust the values inside the css of your used WordPress theme.

**Comment by joergsteinhauer** [comment]
Aaaand this the point :) I need the custom CSS file **inside** of the iframe, **not** in the main-document. 

Is it possible?

**Comment by jangevaare** [comment]
Can't this be done by editing skin/editor.css?

I've done this in the past, but the only problem is that it needs to be redone after each update.

**Comment by Asgaros** [comment]
I dont know, the code should work fine - as long as no other style-definitions (from your theme or other plugins) are overwriting it. As I said before: Its working perfectly fine with the WordPress default themes and with some custom themes I am using as well.

The filter-code which I posted above is the official WordPress filter to apply custom css to the WordPress editor. I cant do any changes to it because it works how it works. You can try to ask in the official WordPress support forums. Maybe they can help you to find a better solution because the forum is using the default WordPress editor as it is without any styling-modifications.

**Comment by joergsteinhauer** [comment]
Ok, thank you for advise.

But one more question, just to clear it up: Does it realy works with default themes? Does it add a CSS file to the iframe then? Or does it add the CSS file to the main-document?

Maybe my theme is too weird (it was bought at template monster), so it does not add the desired CSS file to the iframe. In this case the solution could be a bit dificult, since I don't think that template monster can or want to support issues with third-party-plugins.

can you show me a demo-page where your solution works?

**Comment by Asgaros** [comment]
Hello again,

I implemented my example-code for testing purposes on my official support-website. You can check it out here with an user account when you open the editor.

WordPress implemented the CSS automatically somehow via some injected JavaScript:
![editor](https://user-images.githubusercontent.com/12525671/33783182-f4c15780-dc5b-11e7-8313-fc55c541afbc.PNG)

**Comment by joergsteinhauer** [comment]
Ok, coo, thanks. Just tried it an dit works at your forum. So I guess the problem is in my bought theme.
Good to know and thanks for your help!

**Comment by alexmorco** [comment]
Thanks for sharing this guide, I was looking for help in adding CSS into my WordPress website, It helped me a lot and here's another article that I seen earlier, https://www.cloudways.com/blog/protect-wordpress-with-htaccess/
