### ISSUE TITLE
Reordering Sticky Topics

### ISSUE THREAD

**Issue by kamdhenu** [Asgaros/asgaros-forum#148]
Is there any way of reordering sticky topics?

For example if I create some follow these steps topics:

- Step 1: Install Software
- Step 2: Update Config
- Step 3: Usage Example 1
- Step 4: Usage Example 2

They are appearing in reverse order:

- Step 4: Usage Example 2
- Step 3: Usage Example 1

So is there any way to custom order them?

**Comment by jangevaare** [comment]
They're organized by last post date, like regular topics.

**Comment by Asgaros** [comment]
Hello @kamdhenu 

As already mentioned: By default the topics are ordered by "Last reply". The question is if this makes sense for sticky topics or not because normally the most up2date topics are at the beginning. So I am not sure what would be the most elegant solution for this: Order by last reply, ID or alphabet. I think its about personal taste.

**Comment by Asgaros** [comment]
I added a new filter called _asgarosforum_filter_get_sticky_topics_order_ to the dev-version:
https://github.com/Asgaros/asgaros-forum/commit/8c19ceec59743f255d72d04bdb8e7933e0c12e6e

This allows you to change the ordering of sticky topics (for example by topic-name):

```
function my_sticky_order($order) {
	return 't.name ASC';
}
add_filter('asgarosforum_filter_get_sticky_topics_order', 'my_sticky_order');
```

**Comment by fcmiao** [comment]
@Asgaros Could you give some instructions for a newbie guy about how to put this function you mentioned to work?
I really need my topics in name order, and I have 12.800 topics for all over the Asgaros Forum! 
function my_sticky_order($order) {
	return 't.name ASC';
}
add_filter('asgarosforum_filter_get_sticky_topics_order', 'my_sticky_order');

**Comment by Asgaros** [comment]
Hello @fcmiao 

You have to add this code-snippet to your themes functions.php file. Just put it somewhere at the end (before the ending ?> tag, if there is one).

**Comment by fcmiao** [comment]
Thank you very much Thomas!

2018-04-03 6:28 GMT-03:00 Thomas <notifications@github.com>:
