### ISSUE TITLE
avatar size in widget

### ISSUE THREAD

**Issue by seema84** [Asgaros/asgaros-forum#151]
Hallo Thomas,

mir ist aufgefallen, dass im Widget die Avatare in kompletter Größe geladen werden (was bei einigen mb's schon recht lange dauert). Im Forum selbst werden wie es richtig ist 80x80 kleine Bilder verwendet.
Ich denke es ist sinnvoll auch für das Widget diese 80x80 Bilder zu verwenden.

p.s. schön zu sehen wie sich das Forum weiter entwickelt

**Comment by Asgaros** [comment]
Hallo @seema84 

Das Problem kann ich nicht nachvollziehen. Avatare werden in der angegebenen Größe geladen (standardmäßig 30 Pixel). Von daher nehme ich an, dass das bei dir irgendein anderes Problem (vielleicht im Zusammenspiel mit einer anderen Erweiterung). ist.

**Comment by seema84** [comment]
Warum wird dann nur im widget das Avatar in Originalgröße geladen aber im Forum selbst wird eine andere Datei genommen?

**Comment by Asgaros** [comment]
Vom Code her dürfte das natürlich nicht passieren. Hier der Aufruf innerhalb der Posts:

```
$avatar_size = apply_filters('asgarosforum_filter_avatar_size', 80);
echo get_avatar($post->author_id, $avatar_size);
```

Und hier der Aufruf innerhalb von Widgets:

```
$widgetAvatarSize = apply_filters('asgarosforum_filter_widget_avatar_size', 30);
echo '<div class="widget-avatar">'.get_avatar($element->author_id, $widgetAvatarSize).'</div>';
```

Dementsprechend dürften da maximal 30 Pixel große Dateien geladen werden, es sei denn, du hast mit dem asgarosforum_filter_widget_avatar_size-Filter etwas überschrieben oder irgendeine Erweiterung treibt im Hintergrund sein Unwesen.

**Comment by seema84** [comment]
Im Hintergrund treibt diese Erweiterung sein Unwesen (das zweit meist verwendeste Avatar Plugin).

https://github.com/1ucay/simple-local-avatars/tree/develop/includes

**Comment by Asgaros** [comment]
Falls du dieses Plugin meinst:
https://de.wordpress.org/plugins/simple-local-avatars/

Die letzte Aktualisierung liegt fünf Jahre zurück. Die Wahrscheinlichkeit ist also groß, dass das Probleme bereitet.

**Comment by seema84** [comment]
Ich weiss allerdings gibt es leider keine wirkliche Alternative dazu.

**Comment by Asgaros** [comment]
Versuche es mal mit der folgenden Erweiterung:
https://wordpress.org/plugins/wp-user-avatars/

Diese funktioniert bei mir ohne Probleme.

**Comment by seema84** [comment]
Im Front-End mit Theme My Login übernimmt er die Bilder damit nicht.

**Comment by seema84** [comment]
zur Vervollständigung: ich habe einen funktionierenden fork gefunden
https://github.com/lmbakti/Basic-User-Avatars
