### ISSUE TITLE
Multiple Shortcode Usage returns Same Forum Category for each

### ISSUE THREAD

**Issue by himanshuahuja96** [Asgaros/asgaros-forum#152]
For Example:

[forum forum="17"]
[forum forum="16"]
[forum forum="19"]
[forum forum="11"]
[forum forum="2"]
[forum forum="8"]
[forum forum="18"]
[forum forum="10"]

Gives result for 
[forum forum="17"]

Each Shortcode output is same as the 1st one.

Screenshot Attached
![SEE HERE](https://i.imgur.com/3jWnCun.png)

**Comment by Asgaros** [comment]
Hello @himanshuahuja96 

You can use only one forum-shortcode on a page. If you want to display multiple forums, you should combine them in a category and use the category-parameter instead. Its also possible to include multiple categories, for example:

[forum category="1,10,26"]

**Comment by himanshuahuja96** [comment]
Can you tell me how can I show particular Category to particular membership level?
Or is there is any action which can allow me to check the forum accessibility with my custom code?
Thanks

**Comment by Asgaros** [comment]
You can create an user group and members to it. After it you can go to the structure-settings and limit the category-access to users of this user group.
