### ISSUE TITLE
Style on IPad is wrong - Structure view

### ISSUE THREAD

**Issue by Dogcrafter** [Asgaros/asgaros-forum#156]
![cf7d9f93-1369-44d5-b831-23211bd25061](https://user-images.githubusercontent.com/16384871/36627312-46927a0e-1941-11e8-82db-106cda0a595b.jpeg)

Hello the Style Looks Strange on iPad.
Regards Dogcrafter

**Comment by Asgaros** [comment]
Thanks for the bug report @Dogcrafter 

Making views look nice on all kind of screens is always difficult. I fixed this in the dev-version and it will be included in the next update.
