### ISSUE TITLE
Forum Search does not seem to recognize numbers in a query

### ISSUE THREAD

**Issue by rickbase1** [Asgaros/asgaros-forum#157]
Hey Thomas,

This is the best forum I have ever used.  Well done !!

Just one issue of note so far.

I created a post about getting 404 errors on my site, then I did a search for 404 but it did not return any hits.

I then did a search on errors and it found my post.

FYI, I am running version 1.7.2

Cheers

Rick

**Comment by jangevaare** [comment]
This is likely not a numbers issue but minimum search string length in your database settings.

**Comment by Asgaros** [comment]
Hello @rickbase1 

Yes, @jangevaare is right: The MySQL database only indexes words which are 4 characters or longer. You can find more information about it here:
https://www.electrictoolbox.com/mysql-full-text-index-word-length/

**Comment by rickbase1** [comment]
Thanks for the info Thomas, I was not aware of that Mysql limit.

I will add a note on the site to make the query at least 4 char.

Cheers,

Rick
