### ISSUE TITLE
Post footer display issue

### ISSUE THREAD

**Issue by r3dunlop** [Asgaros/asgaros-forum#161]
Within a post, would it be possible to wrap the message-post <p> in a div? I can't get the footer to either completely display within a post, or not overlap with the post on different screen sizes. This is an issue when the screen is small enough that the footer line-breaks. If there is another CSS solution I would be happy to employ it.

An example where part of the footer is hidden behind the next post:
<img width="534" alt="screenshot 2018-03-20 21 29 08" src="https://user-images.githubusercontent.com/5428160/37681124-17a3c7cc-2c86-11e8-8755-f1dc39b37d0c.png">

**Comment by Asgaros** [comment]
I made a small CSS change which should fix this issue.
