### ISSUE TITLE
Add notification templates

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#164]
Add notification templates for content and subject.

**Comment by ray004** [comment]
Whilst planning for this feature can i ask that you please consider making your emails compatible with the the wordpress plugin "Better Notifications for WordPress".  I like to use this plugin to make sure all the emails sent by my site have the same overall look and feel.
thanks 
ray

**Comment by Asgaros** [comment]
Hello @ray004 

At the moment I dont want to implement integrations to third-party extensions directly into the core of the plugin. There are so many plugins out there which could be connected with each other. Adding code for this directly into the core would bring the need to ensure that everything is working fine after every plugin update - not only Asgaros Forum updates, also updates of connected plugins. In the long term run it would be impossible for me to maintain this.

What I can do is to provide small stand-alone addons or custom implementations which can be installed separately to add this functionality. For a stand-alone addon I cannot tell you yet when I find some time to implement it because at the moment I am working at some other high-priority tasks like SEO-friendly URLs.

**Comment by ray004** [comment]
Hi Asgaros
Ok.  My understanding of how BNFW works is very limited but it works with a lot of other plugins that send email and as far as I know there is not significant integration (ior even none at all) within them. I thought BNFW just intercepts some standard WP function calls (or something) and then wraps the outgoing email with whatever it has been configured to do.
anyway its your decision - i can only make suggestions
ray

**Comment by Asgaros** [comment]
If it just modifies the standard WordPress functions it should work because I dont use custom-code for sending mails. I just pass the subject and the content of the mail to the default wp_mail function.

**Comment by ray004** [comment]
Hi
Must be more to it than that then. It think it must works on pages/posts/custom post actions as it only lists types of posts for it to act on. I thought your topics and replies would be some sort of custom post type but if not that would probably explain it.
thanks anyway I'll just wait till you get email templates and or rss working

**Comment by ray004** [comment]
Hoping these two requests can be incorporated into the email templates you are working on.
1) my forum is only available to logged in members. It is thus nice to address emails to the person eg Dear "first name surname" or Dear "firstname". Be great if WP firstname and lastnames could be template variables.
2) Also I would like to be able to insert the forum name in the template along with the forum topicname so my members know which forum the topic comes from.  ( I can't find a way to get forum_name into the current filters - i can wait for the templates for this feature).

**Comment by Asgaros** [comment]
Hello @ray004 

Templates for new posts/topics notifications are almost ready.

The following placeholders will be available:

- ###USERNAME###
- ###AUTHOR###
- ###LINK###
- ###TITLE###
- ###CONTENT###

Why only ###USERNAME###? Because the user can decide in the backend-profile how his name should get displayed. This ensures that the name in the mails gets displayed the way the user prefers.

Custom placeholders will also be available via hooks which can be added via filter (I dont want to implement hundreds of possible placeholders by default). More about this (example code) when the update will be available.

**Comment by ray004** [comment]
re username ok i understand. So just to cllarify where i am coming from - 
On my site ###USERNAME### doesn't apply as my 'username' is in fact their "'preferred name' space 'surname'" already. They supply me with a 'preferred name' (eg Tom) instead of (eg Thomas) at the time of their membership application and we call them that always (except if legally required not too - never happened on 10 years of operation).
So Dear "'preferred name' space 'surname" , ie Dear ###USERNAME###, isn't as nice as Dear 'preferred name' in the email message text.

also (in my case)
###AUTHOR###  - ok will be used
###LINK### - unlikely to use this link to post as members need to be logged in to read them.
###TITLE### - not sure what this is - if topic/post title then I will use it. 
###CONTENT### - if topic/post text then probably won't use it (as I want member so login to read since they must login to be able to reply).

I still need a way to identify which forum the topic/post has come from (ie forum name) in either the title (if as above) or in the email message text itself). I don't have a single forum (such as support forum). i currently have 5 categories with 13 forums so it is important to identify the source location of the topic. So hopefully I can use your custom placeholders to do this.
I guess I may also be able to use these custom placeholders to get my 'preferred name' placeholder too.

Also are the templates going to allow
1) customisation of the email subject (as well as the message text)
2) and allow html code so that emails are delivered as html instead of plain text?

thanks

**Comment by Asgaros** [comment]
Hello again @ray004 

Again talking about the username: You say you use "FIRSTNAME SURNAME" as the username. That means that you can set the "Display name publicly as" in their profile to "FIRSTNAME SURNAME" as well.

The Asgaros Forum notifications always use the name based on the "Display name publicly as" setting. So with this configuration this would already work as intended, right?

**Comment by ray004** [comment]
Hi Thomas
I don't use the display name at all. and I don't allow members to edit their profile either - no need for them to do so, at least not at the moment - i never say never though.
So yes in my case the username, nickname and display name are the same by default.
I assume that if they could edit their profile the would be able to change firstname and surname anyway.

I've never investigated what/how/where WP uses nickname or display name either. I've never had to as the membership plugin i use (wp members by chad butler) doesn't seem to use them either and it gives me shortcodes(placeholders) to access firstname and surname, email address etc as i need too in his email message templates.

I wonder about setting email subject as a setting. It would be real nice (but probably a future or not at all   feature) that both the subject and the message text were "one template" and I could then have a 'default template plus optionally specific templates per forum.  I could also then use placeholders in the subject line if I wanted too. This would also be real nice in the future if/when you provide the feature of 'forum moderators', ie one or two people who can 'moderate' a forum (in my case special interest group forums) and thus have customised message that are appropriate to that forum.  
But I guess I am getting ahead of things now as I can work with a single template now.

thanks again
Richard

**Comment by ray004** [comment]
further to "So yes in my case the username, nickname and display name are the same by default."
When I add new users in to WP I only set firstname and surname and then join them up to form their username.  WP assigns the default values (I assume from  firstname and surname as supplied ) to nickname and display name and they just happen to be the same as my username.

**Comment by Asgaros** [comment]
I guess this is something which would be more suitable for an additional notification-extension instead of adding this to the core of the plugin. I want to keep the core of the plugin as simple as possible. Otherwise people start to experiment with the settings and at the end nothing is working anymore because they dont know what they do caused by difficult settings.

This already happens often with the current access/usergroup implementation so people suddenly cant see areas anymore because they dont "get" that they adjusted the access-settings. I am also a little bit worried about mail-templates, because things can go wrong if people start to use wrong html-markup or start to add "strange" placeholders by themselfes breaking the entire functionality.

Lets see how things will go. I will close this ticket for now because the first version of templates have been implemented with the last commit. I am sure that more enhancements will come in the future based on a wider feedback. :)
