### ISSUE TITLE
Meta Variablen in eigene Tabelle schreiben

### ISSUE THREAD

**Issue by springers54** [Asgaros/asgaros-forum#165]
Ich habe mehr als 9000 Nutzer und eins deiner Foren für 2 Nutzergruppen.
Ich habe mir die Meta-Tabelle angesehen, die sehr unübersichtlich wird durch die vielen Einträge, die das Forum erzeugt.
Wenn ich es richtig verstehe, legt jeder gelesene Beitrag eine Metazeile an. Nehmen wir mal an, ein Forum hat 1000 Beiträge und 9000 Nutzer würden nur 10% davon lesen, dann wären das schon ... Zeilen.

Ich halte es für sinnvoller, eine eigene wp_forum_usermeta-Tabelle zu benutzen.
Das würde die Sache übersichtlicher machen.

**Comment by Asgaros** [comment]
Hallo @springers54 

An dem Verhalten und dem Weg, wie die Daten gespeichert werden, kann ich leider nichts ändern da ich die offiziellen WordPress API-Funktionen benutze. Diese kümmern sich zum Beispiel auch automatisch um das Aufräumen von Daten, wenn ein Benutzer gelöscht wird, etc.

Sollte ich das komplett auf ein eigenes System umstellen, müsste ich WordPress-Funktionen, die schon existieren, für den selben Verwendungszweck neu implementieren. Der Datenbank ist es auch egal, wieviele Daten darin liegen oder ob diese fürs menschliche Auge unübersichtlich erscheinen. Selbst bei Millionen Einträgen ist ein Zugriff dank eindeutigen IDs und Referenzierungen innerhalb von Sekundenbruchteilen möglich.

Siehe hier die offizielle Dokumentation:
https://codex.wordpress.org/WordPress_Taxonomy
