### ISSUE TITLE
Beiträge auf anderen Nutzer verschieben erlauben

### ISSUE THREAD

**Issue by springers54** [Asgaros/asgaros-forum#166]
Falls es Problem mit einem Account gibt und man darum einen neuen erstellen muss, dann wäre es besser, dass man entscheiden kann, ob man die Forumbeiträge ebenfalls dem neuen Account zuordnet.

Bei Seiten und Beiträgen geht das ja auch. Ansonsten hat man das Problem, dass im Forum nur gelöschter Benutzer erscheint. Wenn man dann mehrere gelöscht hat, ist es gar nicht mehr zuzuordnen.

**Comment by Asgaros** [comment]
Entschuldige erst einmal die Schreibweise, aber chinesische Tastaturen haben leider keine Umlaute.

Ich habe mich fuer den Moment erstmal dagegen entschieden, eine solche Funktion zu implementieren. Mir persoenlich ist das Missbrauchspotential dafuer zu hoch, wenn diese Funktion problemlos ueber den Adminbereich erreicht werden kann. So koennten zum Beispiel unangemessene Beitraege absichtlich ungeliebten Benutzern zugeordnet werden.

Natuerlich kann man das Argument entgegenstellen, dass man dies auch einfach ueber die Datenbank bewerkstelligen kann. Dafuer ist die technische Huerde aber ungleich hoeher, und es benoetigt etwas Hintergrund wissen fuer solch administrative Zwecke, so dass die Gefahr einer Ausnutzung verringert wird.

Ebenso besteht bei einer unsachgemaessen Benutzung die Gefahr, dass Beitraege faelschlicherweisse falsch zugeordnet werden. Danach die Beitraege wieder auseinanderzufriemeln duerfte beinahe ein Ding der Unmoeglichkeit sein.

Dennoch: Falls unbedingt der Bedarf fuer solch eine Funktion - die nur in Ausnahmefaelle benoetigt werden duerfte - besteht, koennen die Zuweisungen immernoch manuell in der Datenbank mit einem Tool wie phpMyAdmin manuell geaendert werden. Der Einzeiler dafuer sieht folgendermasen aus:

`UPDATE `wp_forum_posts` SET `author_id` = 2 WHERE `author_id` = 1;`

- 2: Die Benutzer-ID, denen die Beitraege zugewiesen werden sollen
- 1: Die Benutyer-ID des urspruenglichen Benutzers

**Comment by springers54** [comment]
Vielen Dank für den Hinweis. Ich verstehe deine Bedenken. Trotzdem habe ich den Fall, dass ich unter verschiedenen Accounts arbeite, dies aber nicht noch über das Forum publizieren möchte. Da hilft mir dann dein Script schon. 
Ich werde es probieren.

**Comment by Asgaros** [comment]
Gute Neuigkeiten: Ich habe mich - aufgrund mehreren Nachfragen anderer Benutzer - nun doch dazu entschieden, dieses Feature zu implementieren. Diese Funktion wird mit dem nächsten Update v1.13.3 hinzugefügt welches ich nächste Woche veröffentlichen möchte.
