### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by r3dunlop** [Asgaros/asgaros-forum#168]
Since the new update users are receiving a gateway timeout when they create a new topic. Is there a chance that some of the new subscription logic is causing this timeout? Our server may not be able to handle sending out all of the subscription emails in one shot. Could this be the root of the problem?

Edit: The users post still get sent through, they just aren't redirected properly. If a user tries refreshing, it resubmits the form and we get duplicate topics.

**Comment by Asgaros** [comment]
Hello @r3dunlop 

Have you tried to disable the subscription-functionality for testing-purposes? Does this fix the problem? If so, I will have a look at the performance of the query.

**Comment by r3dunlop** [comment]
Hi @Asgaros 
Subscriptions off worked perfectly. Turning them back on still causes the error.
Just noticed your edit. Thank you!

**Comment by Asgaros** [comment]
Hello @r3dunlop 

I just fixed this issue in the latest development-version. If you need to apply the fix asap, you can download it here:
https://github.com/Asgaros/asgaros-forum/archive/050e1b6851527dbe777de5e75218222ce99540bf.zip

It would be nice if you could give it a try and leave me some feedback after testing to ensure that it is fixed for sure. Just replace the plugin-files with a FTP-application on your server.

Anyway: the update will be available in the next 48 hours.

**Comment by r3dunlop** [comment]
Works like a charm. Thank you!
