### ISSUE TITLE
wp_forum_posts table not created during install on SQLServer

### ISSUE THREAD

**Issue by pfkoss** [Asgaros/asgaros-forum#177]
having an issue where the wp_forum_posts table did not get created on an SQLServer install.  Is there anyway you can post the DDL for the table so that I can manually create the table.

**Comment by Asgaros** [comment]
Hello @pfkoss 

Can you give some details on why the table is not created? Maybe we can find a fix for this.

The structure is defined in _includes/forum-database.php_:

`$sql[] = "CREATE TABLE ".$this->tables->posts." (
            id int(11) NOT NULL auto_increment,
            text longtext,
            parent_id int(11) NOT NULL default '0',
            date datetime NOT NULL default '0000-00-00 00:00:00',
            date_edit datetime NOT NULL default '0000-00-00 00:00:00',
            author_id int(11) NOT NULL default '0',
            author_edit int(11) NOT NULL default '0',
            uploads longtext,
            PRIMARY KEY  (id)
            ) $charset_collate;";`
