### ISSUE TITLE
Text verschwindet nach Upload Fehler

### ISSUE THREAD

**Issue by Dogcrafter** [Asgaros/asgaros-forum#179]
Hallo,

ist der Upload von Bildern auf z.b. 1 MB eingeschränkt und der User versucht irrtümlich ein größeres Bild hochzuladen, so kommt es zu einer Fehlermeldung. So weit, so gut. Leider wird aber auch der zuvor eingegebene Text gelöscht. Was für den Anwender sehr ärgerlich ist.

Grüße Dogcrafter

**Comment by Asgaros** [comment]
Hallo @Dogcrafter 

Das sollte eigentlich nicht passieren und der Text wird bei mir nach einer Fehlermeldung auch weiterhin korrekt angezeigt.

Welches Theme verwendest du denn?

**Comment by Dogcrafter** [comment]
Seltsam, ich kann den Fehler nun auch nicht mehr nachvollziehen.
Sorry Dogcrafter
