### ISSUE TITLE
Last topics widget

### ISSUE THREAD

**Issue by ironboys** [Asgaros/asgaros-forum#18]
Здравствуйте. Есть ли виджет или шорт код для вывода последних трех тем на главной с автором и временем создания. Также как поменять язык на форуме ?

Hello. Whether there is a widget or shorts a code for a conclusion of the last three subjects on main with the author and time of creation. Also how to change language at a forum?

**Comment by Asgaros** [comment]
Hello ironboys.

Actually there is no widget to show the subjects and authors of the last three posts. Maybe I can add one Widget in a future release.

The forum is using the language which is defined as your "Site Language" in your WordPress General Settings. But at the moment there are only language files for english, finnish and german. If you use another language, the english language file is used as default.

If you want to translate this plugin into another language, you can do this at this site:
https://translate.wordpress.org/projects/wp-plugins/asgaros-forum

**Comment by ironboys** [comment]
And when approximately there will be a new release? It would be good if made a widget of the last subjects

**Comment by Asgaros** [comment]
I am not sure yet when I will integrate this functionality. I will leave a comment in this ticket when I have more information for you. :)

**Comment by ironboys** [comment]
Without conclusion of subjects to a forum main somehow remains imperceptible on the site. There is an opportunity for an additional fee to make a widget of the last subjects? the site is visited and the forum is empty because of that that isn't visible to those and that the forum is. :)

**Comment by Asgaros** [comment]
Yeah I will work on it and include it in the next release.

**Comment by ironboys** [comment]
And the approximate term of new release it is known? Week? Month?

**Comment by Asgaros** [comment]
~1 week I think.

**Comment by ironboys** [comment]
I will be hopes and to wait :-) Thank you

**Comment by Asgaros** [comment]
@ironboys 

I added a first version of a Recent Forum Posts Widget to the developer version. Is it okay or do you have some improvement suggestions?

![widget](https://cloud.githubusercontent.com/assets/12525671/12280357/9312879a-b98d-11e5-954e-c9f86c4ca64c.PNG)

**Comment by ironboys** [comment]
если вывести аватар автора, ник автора темы,  название темы и дата публикации. например типа так

would look nice if the output picture of the author, Nick's theme, topic name, and date of publication. example http://prntscr.com/9phd52

**Comment by ironboys** [comment]
and how to install the widget? You can get the files to replace

**Comment by ironboys** [comment]
Installed.  I in a widget if to press a subject have here such link ironboy.ru/9#postid-13. Why there is no full way on a forum at me? Where to specify?

**Comment by Asgaros** [comment]
Maybe I can include the author name but the avatar is too much. It will look ugly anyway when not every user has an avatar.

Maybe there are some problems because its not a final version yet. Please wait for the official release. :)

**Comment by ironboys** [comment]
The correct way on a subject only in a forum, on main the way which is cut down isn't enough for a t.a /forum?view=thread. As asgarosforum I should fill something it seems

**Comment by ironboys** [comment]
Temporarily I put a full way in a widget manually, I will wait so to release

**Comment by Asgaros** [comment]
Yeah I will patch it soon.

**Comment by ironboys** [comment]
Thank you

**Comment by Asgaros** [comment]
I submitted an update to the development version. On the widget you have to select the page on where the forum is located. Can you check it please?

**Comment by ironboys** [comment]
Brings a mistake to lines 41 writes Fatal error: Call to undefined method
asgarosforum:: get_widget_link ()

**Comment by Asgaros** [comment]
Have you replaced the file includes/forum.php?

**Comment by ironboys** [comment]
Now works. And links too are right

**Comment by Asgaros** [comment]
Okay, thank you for the feedback. I think I can release this first version of the widget today or tomorrow in the 1.0.3 release. :)

**Comment by ironboys** [comment]
I noticed that not the author of a subject and last who left the message is specified

**Comment by Asgaros** [comment]
Yeah thats right. The widget shows the X "Recent Forum Posts".
