### ISSUE TITLE
several URl forum in shortcode are broken on 1.9

### ISSUE THREAD

**Issue by alexsebbane** [Asgaros/asgaros-forum#181]
on our website, we use a shotcode [forum forum="2"] , all the links are broken. 

the version 1.8 is ok : 
http://www.pararfogos.org/index.php/temoigner/

**Comment by Asgaros** [comment]
Hello @alexsebbane 

Disabling seo-friendly urls should solve that problem for the moment.

I already fixed a bug in the latest development-version which caused problems when using a custom permalink-structure containing **/index.php/** inside it.

Please try to replace the plugin-files on your server (via a FTP-application) with the following ones:
https://github.com/Asgaros/asgaros-forum/archive/a35bd7a8250f4c46317c1dd05064af6bdc87a85d.zip

I would be happy to get some feedback if this development-version corrects this issue so I can release an update as soon as possible.

**Comment by Asgaros** [comment]
Hello @alexsebbane 

I just released version 1.9.1 which should fix that bug.
