### ISSUE TITLE
Unread Topics-View

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#182]
Add an "Unread Topics"-View. If you click on an item listed there, it should bring you to its first unread post.

**Comment by hmbelial** [comment]
is this function to jump to the first unread post not be available?

**Comment by Asgaros** [comment]
@hmbelial Clicking on a link there brings you to that topics first unread post.

**Comment by hmbelial** [comment]
thanks, i noticed it!!

it will be more useful on the top of the forum instead on the bottom imho

BTW, really marvellous work on ASGAROS forum!!!
