### ISSUE TITLE
Post on mobile phone

### ISSUE THREAD

**Issue by Dogcrafter** [Asgaros/asgaros-forum#184]
Hi,
some forums users report that their posts, which they have entered on the smartphone, do not appear. But as admin I get an email notification with the text. 
Mobil: Samsung Internet, Android

Regards Dogcrafter

**Comment by Asgaros** [comment]
Hello @Dogcrafter 

This could be a caching-issue. Can you see the created posts in your forum?

**Comment by Dogcrafter** [comment]
Hi,

no, so posts are not shown. 

Greetings Dogcrafter

**Comment by Asgaros** [comment]
Can you verify if that problem occurs when users added emojis to the posts content?

**Comment by Dogcrafter** [comment]
Yes, the user added one Emoji.

**Comment by Asgaros** [comment]
This seems to be a configuration problem with your database. Please have a look at the following article which explains the problems and contains information on how to fix them:
https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by Dogcrafter** [comment]
This was the case! Thanks for the help!
