### ISSUE TITLE
Mention emails when subscribed

### ISSUE THREAD

**Issue by r3dunlop** [Asgaros/asgaros-forum#186]
Would it be possible to do a check on whether someone is subscribed to a topic when they are mentioned? Currently, if someone is subscribed, they receive two emails: One for being mentioned, and another for being subscribed. Ideally they would only get one or the other.

**Comment by Asgaros** [comment]
Hello @r3dunlop 

I am aware of the situation that users can get multiple mails for the same subject in the current configuration.

So when the situation occurs that an user could get two mails, should he receive:

- a mail that he got mentioned?
- or a mail that there is a new post/topic?

Which way do you prefer? And why?

**Comment by r3dunlop** [comment]
I think just that they got mentioned. To me, being mentioned in a post takes precedence. If you are mentioned, you are typically important to the current thread, while a subscription usually just means you are watching a thread.  That’s just my preference though.

**Comment by Asgaros** [comment]
Good news: The suggested change (dont send another mail when an user already gets notified because he got mentioned) will be included in the upcoming v1.13 release which will be available during this month (January).

**Comment by r3dunlop** [comment]
That’s great news. Thanks for your effort!
