### ISSUE TITLE
Styling IPad Hochformat 

### ISSUE THREAD

**Issue by springers54** [Asgaros/asgaros-forum#189]
Habe eben gesehen, dass das sehr ungünstig aufgeteilt ist.
![6c1627dc-c825-40e2-9b65-07e6cd3e75f3](https://user-images.githubusercontent.com/6114076/46866434-ac9ccd00-ce21-11e8-9ba8-7f7c9e3f2e1c.png)

**Comment by Asgaros** [comment]
Hallo @springers54 

Ja, momentan gibt es noch sehr viele Baustellen, da ich mit vielen Dingen nicht zufrieden bin. Deshalb arbeite ich momentan an vielen kleineren Verbesserungen, um vorhandene Funktionen zu optimieren - darunter zum Beispiel die Filterfunktion fuer die Mitgliederliste, Templates fuer Mail-Benachrichtigungen, etc.

Das Beitrags/Themen Design moechte ich auch nochmal vereinfachen und umgestalten, damit der Platz besser genutzt werden kann und das Design etwas minimalistischer - aber gleichzeitig ansprechender - wird. Davon wird dann auch das Mobile-Theme profitieren.

Dies wird sich aber noch eins-zwei Updates hinziehen, da ich nicht zuviele Aenderungen auf einmal machen moechte. Lieber langsam und vorsichtig, um moegliche Fehler dann schnell zu beheben statt ueberstuerzt - was am Ende zu Chaos an allen moeglichen Fronten fuehrt.

**Comment by Asgaros** [comment]
Hallo @springers54 

Anbei ein Screenshot mit den momentanen Anpassungen, die mir fuer die Hochkant-Anzeige beim iPad vorschwebt. Ich habe versucht, den verwendeten Platz soweit wie moeglich zu reduzieren. Ein kurzes Feedback waere super!
![design update](https://user-images.githubusercontent.com/12525671/47712568-0bac6f80-dc73-11e8-9055-27481d315bfc.PNG)

**Comment by springers54** [comment]
Finde ich schon sehr viel aufgeräumter so. Wüsste nicht, wo man noch etwas sparen kann.

 * [ ] ist mir neulich aufgefallen: Ich habe sehr viele Forumsgruppen. Beim Hochformat überdecken diese das Benutzersuchfeld in der Benutzerverwaltung, im Querformat nicht. Schau mal, ob das bei dir auch so ist. Screen muss ich sonst nachliefern.

**Comment by Asgaros** [comment]
@springers54 Kann ich bei mir nicht nachvollziehen. Aber es kann gut sein, dass der Fehler nebenbei bei meiner Entwicklungsversion schon behoben wurde. Ein Screen waere aber dennoch sehr hilfreich.
