### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by ironboys** [Asgaros/asgaros-forum#19]
Очень понравился форум, думаю будет один из лучших в будущем. Захотел немного помочь и начал переводить на русский язык,  посмотришь и активируешь. Как закончу установлю русский на свой форум. Спасибо за плагин

Very much the forum was pleasant, I think there will be one of the best in the future. I wanted to help a little and I started translating into Russian, you will look and you activate. As I will finish I will establish Russian on the forum. Thanks for a plug-in

**Comment by ironboys** [comment]
I finished translates into Russian, the request to check and activate

**Comment by Asgaros** [comment]
Great! Thank your very much for your translation. I will add the translation file to the next version. :)

**Comment by ironboys** [comment]
You couldn't activate Russian translation, I want to download and establish on the forum

**Comment by Asgaros** [comment]
Yes, some WordPress Translation Moderator has to approve your translations first. After that your WordPress should automatically download the translation files with your updated translations.

**Comment by Asgaros** [comment]
Hello @ironboys 

I added a first version of the translation files to the development version of this plugin (https://github.com/Asgaros/asgaros-forum/commit/39076cacb7b0c3c5c6abb87a82e5668d4f18e9d1).

Can you please check the translation files? I think some strings are a little bit too long, maybe you can make them more short.

[ru_RU.zip](https://github.com/Asgaros/asgaros-forum/files/85783/ru_RU.zip)

Thanks!

**Comment by ironboys** [comment]
Спасибо,  с переводом все нормально. Установил. Теперь бы виджет или shortкод для вывода последних тем и будет идеальный форум :)

Thanks, with the translation everything is normal. I established. Now the widget or shortkod for a conclusion of the last subjects will also be an ideal forum :)

**Comment by Asgaros** [comment]
Okay, thank you for your reply. I will try to add this widget to one of the next versions (maybe 1.0.3 or 1.0.4).
