### ISSUE TITLE
Mixed language 

### ISSUE THREAD

**Issue by Dtrieb** [Asgaros/asgaros-forum#190]
On the new Update (1.11.0) there is mixed language (see screenshot)
![chrome_2018-11-18_17-43-02](https://user-images.githubusercontent.com/3650284/48675472-7574b680-eb59-11e8-9322-2edfa6ab8e0f.png)

**Comment by Asgaros** [comment]
Hallo @Dtrieb 

Dieser Fehler trat auf, da die deutschen Sprachdateien für das neue Update noch nicht aktualisiert wurden. Dies sollte nun passiert sein - die neuen Dateien sollten nun über den WordPress-Updater angeboten werden. Falls nicht, bitte einmal die Suche manuell "triggern".

**Comment by Dtrieb** [comment]
Sorry!

Aber auch mit dem Update auf 1.11.1 ist keine deutsche Sprache gekommen.

**Comment by Asgaros** [comment]
@Dtrieb Die Sprachpakete sind auf jeden Fall vollständig:
https://translate.wordpress.org/projects/wp-plugins/asgaros-forum

Wann und wie oft WordPress die aktualisiert liegt nicht in meiner Hand. Das kann immer mal bis zu 48 Stunden dauern.
