### ISSUE TITLE
Ungelesene Themen

### ISSUE THREAD

**Issue by Dogcrafter** [Asgaros/asgaros-forum#191]
Hallo,

die ungelesenen Themen, sollten genauso gefiltert werden, wie die Aktivitäten. Bei den Aktivitäten werden Posts aus nicht sichtbaren Bereiche ausgefiltert, schaut man sich das Forum unangemeldet an, ebenso befinden Widgets. Bei den ungelesenen Themen leider nicht.

Grüße Dogcrafter

**Comment by Dogcrafter** [comment]
Hallo,

keine Caching aktiv. Gehe auf die Seite www.tipi-Camping.de und schau dir die ungelesenen und die Aktivitäten an. Bei den ungelesenen, sind alle ohne Ort, die aus dem nicht sichtbaren Bereich, also nur für angemeldete User.
Siehe auch Screenshots
Grüße Dogcrafter
Am 3. Dez. 2018, 16:27 +0100 schrieb Thomas <notifications@github.com>:

**Comment by Asgaros** [comment]
Hallo nochmal,

editiere bitte einmal die folgende Datei:
_wp-content/plugins/asgaros-forum/includes/forum-unread.php_

Finde diese Zeile (müsste circa Zeile ~270 sein):
`$unread_topics = $this->asgarosforum->db->get_results("SELECT MAX(p.id) AS max_id, t.id AS topic_id, t.name AS topic_name, t.sticky, t.closed, f.id AS forum_id, f.name AS forum_name FROM {$this->asgarosforum->tables->posts} AS p LEFT JOIN {$this->asgarosforum->tables->topics} AS t ON (t.id = p.parent_id) LEFT JOIN {$this->asgarosforum->tables->forums} AS f ON (f.id = t.parent_id AND f.parent_id IN ({$ids_categories})) WHERE p.date > '{$this->get_last_visit()}' GROUP BY p.parent_id ORDER BY MAX(p.id) DESC;");`

Ersetze sie mit:
`$unread_topics = $this->asgarosforum->db->get_results("SELECT MAX(p.id) AS max_id, t.id AS topic_id, t.name AS topic_name, t.sticky, t.closed, f.id AS forum_id, f.name AS forum_name FROM {$this->asgarosforum->tables->posts} AS p LEFT JOIN {$this->asgarosforum->tables->topics} AS t ON (t.id = p.parent_id) LEFT JOIN {$this->asgarosforum->tables->forums} AS f ON (f.id = t.parent_id) WHERE f.parent_id IN ({$ids_categories}) AND p.date > '{$this->get_last_visit()}' GROUP BY p.parent_id ORDER BY MAX(p.id) DESC;");`

Gebe mir danach bitte Feedback, ob dies den Fehler beseitigt.

**Comment by Dogcrafter** [comment]
Ja, das löst das Problem!
Danke

**Comment by Asgaros** [comment]
Danke für die Rückmeldung! Den Fehler hatte ich tatsächlich vorhin schon unbeabsichtigt - im Zusammenhang mit einem anderen Fehler - behoben, weshalb ich ihn bei mir nicht mehr reproduzieren konnte.

Ein entsprechender Fix wird natürlich auch im kommenden Update enthalten sein.
