### ISSUE TITLE
Feature request: mention autocomplete in editor

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#201]
Thanks for your continued development of this plugin!

Mention autocomplete in the editor would be a very handy feature to ensure that a mention was written without error the first time a post is made. Especially as I believe if a post is edited to fix a typo in a mention, the notification email does not send in that instance.

Cheers.

**Comment by Asgaros** [comment]
By checking how other plugins are doing this I found an existing solution which is used inside of BuddyPress. It is based on the following jQuery-addon:
https://github.com/ichord/At.js/releases/tag/v1.5.4

The JavaScript-implementation is available here:
https://github.com/buddypress/BuddyPress/blob/master/src/bp-activity/js/mentions.js

I think that I can maybe re-use some of the code and add the required REST-endpoints to the forum-system.

A possible version to add this enhancement could be v1.14.10 - so it will definitely become available in one of the next updates.
