### ISSUE TITLE
Conflict with the Yoast SEO plugin (force rewrite title function)

### ISSUE THREAD

**Issue by Pacjonek** [Asgaros/asgaros-forum#209]
When the _Force Rewrite Title_ function in the Yoast SEO plugin is activated, the <title></title> tags don't appear in the <head></head> tags of the html document.

**Comment by Asgaros** [comment]
Hello @Pacjonek 

Can you give some more details about the "Force Rewrite Title" option? I cant find it anywhere in the settings.

Beside of that: By default Asgaros Forum disables Yoast SEO on all forum-pages because Asgaros Forum uses built-in SEO-functionality. Yoast SEO does not know how Asgaros Forum internally works so it cannot set the correct title and meta-tags. For this reason its in general a good idea to disable Yoast SEO on the page which contains your forum-shortcode.

**Comment by Pacjonek** [comment]
This option is available in the SEO > Search Appearance > Force rewrite titles
How to exclude only one page from the Yoast SEO? I can't not find this option

**Comment by Asgaros** [comment]
I dont have this option there:

![yoast](https://user-images.githubusercontent.com/12525671/53955590-b4fbea00-40d9-11e9-9de1-15bbd52b39c7.PNG)

Are you using the latest version of both Yoast SEO and Asgaros Forum?

**Comment by Pacjonek** [comment]
![image](https://user-images.githubusercontent.com/8076994/53955685-f1c7e100-40d9-11e9-9642-68e8cb9f570b.png)
Yes, newest version of Yoast SEO and Asgaros Forum

**Comment by Asgaros** [comment]
The "Fore rewrite titles" option is only there when your theme doesnt support title-tags by default. Have you checked if enabling this option is necessary for your site? If so, please try to contact the Yoast support and ask them on how to disable this option for certain pages. Maybe there is a filter or setting for this. I already disable meta-generation of Yoast SEO on Asgaros Forum pages by default but it seems that this does not have any effect on the title when this option is enabled.

If you create a topic in their support-forum please leave me a link here. I am curious about the solution and maybe I can implement a workaround if there is any.

**Comment by Pacjonek** [comment]
Thanks to your tip I found that the problem is my theme that is not support 'title-tag'.
I added `add_theme_support( 'title-tag' )` to function.php of my child theme and removed whole `<title></title>` tags in the header.php and now everything is works correctly.
Thank you.

**Comment by Asgaros** [comment]
I am glad to hear that its working now!
