### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by victorrms2** [Asgaros/asgaros-forum#210]
Hello!

I'm Victor and I use Asgaros Forums in my Wordpress Website. Configuring it I noted that the Portuguese Translation of it is not really accurate. For example, this top bar is fully in english:

![image](https://user-images.githubusercontent.com/48393202/54156047-27dfca80-4424-11e9-9fc6-3c589f2c5ddf.png)

Also, down there are some English words:

![image](https://user-images.githubusercontent.com/48393202/54156076-36c67d00-4424-11e9-804e-6e29432e0a5d.png)

I want to help Asgaros with translation. How can I do it? Thanks for the software!

**Comment by Asgaros** [comment]
Hello @victorrms2 

You can help to translate Asgaros Forum via the official WordPress Plugin Translation website:
https://translate.wordpress.org/projects/wp-plugins/asgaros-forum

If you are a native speaker of Portugese and if you are interested in becoming a Plugin Translation Editor for Asgaros Forum (who can approved translations) please let me know.

**Comment by victorrms2** [comment]
I'm interest in helping Asgaros Forum with translation. As an open-source software, it is driven by the community too, and I feel like I need to help with anything I can.

But I am a student and sometimes I have a busy week, so I can not help some days. If being a Plugin Translation Editor needs to have free time everyday, I really can not. But if this job is done regularly but not everyday, I want to join in.

**Comment by victorrms2** [comment]
In the next days I will start translating it. Today I can not but for sure, this week, I will.

**Comment by Asgaros** [comment]
No, its not a every-day job. A PTE just adds missing translations for his spoken language if he has time. Its absolutely up to you. :)

**Comment by victorrms2** [comment]
So I am interested on it!

**Comment by Asgaros** [comment]
Okay, great. I will send request to the WordPress translation-team as soon as you added a few translations so they can add you as a PTE.

**Comment by victorrms2** [comment]
I translated a lot of things there, can you add me ad PTE?

**Comment by Asgaros** [comment]
@victorrms2 

Can you tell me your username on wordpress.org so I can send a request to the translation-team?

**Comment by victorrms2** [comment]
It is almost like mine here. It is victorrms

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 7 de abr de 2019 23:50, Thomas escreveu:

**Comment by Asgaros** [comment]
@victorrms2 

I just made a request for you here:
https://make.wordpress.org/polyglots/2019/04/08/hello-polyglots-i-am-the-488/

**Comment by victorrms2** [comment]
Will it take much time? I still haven't received anything

**Comment by Asgaros** [comment]
Hello @victorrms2 

Unfortunately, I dont have any influence on the speed because only wordpress.org-moderators can set new translation-editors. Maybe you can also leave a message under my linked post above, so they can see it.
