### ISSUE TITLE
Avatar size is different

### ISSUE THREAD

**Issue by Dtrieb** [Asgaros/asgaros-forum#214]
Hey!

Can you look at: [https://moschuss.de/forum/](https://moschuss.de/forum/)

There are the Avatar size is different.
Need help.

**Comment by Asgaros** [comment]
Hallo @Dtrieb 

Diesen Fehler habe ich bereits in der aktuellen Entwicklerversion behoben und der entsprechende Patch wird in dem nächsten Update enthalten sein. Bitte füge in der Zwischenzeit den folgenden Code in Forum -> Appearance -> Custom CSS hinzu:

```
#af-wrapper .forum-poster-avatar img,
#af-wrapper .topic-poster-avatar img {
    height: 40px; /* comp */
    width: 40px; /* comp */
    margin: 0; /* comp */
    padding: 0; /* comp */
}
```
