### ISSUE TITLE
Create Table Forum_Polls_Options Error

### ISSUE THREAD

**Issue by jvanalst** [Asgaros/asgaros-forum#217]
Hi,

We tried to install 1.14 last night and received the following error: 

> WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'option varchar(255) NOT NULL default '',
>             PRIMARY KEY  (id)
>          ' at line 4 for query CREATE TABLE wp_forum_polls_options (
>             id int(11) NOT NULL auto_increment,
>             poll_id int(11) NOT NULL default '0',
>             option varchar(255) NOT NULL default '',
>             PRIMARY KEY  (id)
>             ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

It turns out "**option**" is a reserved word in (at least some versions of) MySQL.

All that's needed are some backward `scare quotes`.

**Comment by jvanalst** [comment]
See:
https://github.com/Asgaros/asgaros-forum/pull/218

**Comment by Asgaros** [comment]
Hello @jvanalst 

Thank you for the info! Unfortunately the wbDelta does not support apostrophes or backticks around field names. So I had to revert your change and add some kind of migration-logic to fix this problem.

I will release an update soon.
