### ISSUE TITLE
[Security] Vulnerability Report

### ISSUE THREAD

**Issue by xpirt** [Asgaros/asgaros-forum#219]
Hello @Asgaros,

there is a vulnerability in the latest version of the plugin. I've sent an email to developer[at]thomasbelser.net. Please let me know if it's the correct email.

Andrei

**Comment by Asgaros** [comment]
Hello @xpirt 

Yes, this email is correct. I just sent you an answer. I would be happy if you could share more information with me about this issue so that I can fix it as soon as possible.

**Comment by xpirt** [comment]
Ok. Closing this.
