### ISSUE TITLE
Integration: BuddyPress

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#224]
Integration: BuddyPress

**Comment by migulinek** [comment]
What about options in BP (1) `Erase Personal Data` and (2) `Export Personal Data`? If user will wish to remove his account, what about posts and topics of his own? How about consistency of forum's discussion? What do you think about that?

**Comment by Asgaros** [comment]
Hello @migulinek 

Adding an option to remove posts of an user is really problematic for forums. Removing the posts of an user will destroy the entire discussion-structure inside existing topics. Another problem is, that posts could be inside of another users posts based on a quote. In this case - of course - I cannot delete the posts of those other users as well.

Because of those issues, I currently dont have any plans for supporting this problem. By default, posts are editable by their authors so an user still has the possibility to edit and remove the content inside of them. After deleting an user, the author will be changed automatically to "Deleted User".

**Comment by migulinek** [comment]
There is an example snippet from `wp_forum_posts` table:

\<blockquote\>
\<div class=\"quotetitle\"\>Quote from \<a class=\"profile-link\" href=\"somehost/.../profile/user/\"\>user\</a\> date 7 October 2011, 13:10\</div\>
Hi Piter :-)
\</blockquote\>

There are two steps to clean up the personal data when the user delete his account:

1. Replace href attribute of a.profile-link by a #
2. Replace the username inside anchor by **erased user** string.

It's possible to do that by regexp, but you have to get an information from a lawyer about GDPR issues in that situations. It's not a development problem but rather a legal one.

If you will be clear about that, we should create a function `getPostsWithErasedUserQuotation` which should return an array of rows from that table to update **text** field by a new one. The array of objects should have two properies ID and text, and next function `updatePostsWithErasedUserQuotation` should replace the "personal data" personal data scattered throughout the forum.

**Comment by Asgaros** [comment]
Hello @migulinek 

Yes, I am aware that its possible with regular expressions. However, quotes are not the only thing which must get considered. For example:

- its possible that an user got mentioned inside a post.
- the profile-link is also not always included inside of a quote because this functionality is optional
- there is the risk, that the quote-container somehow got modified by a post-author because it can easily get changed (by mistake or purpose) inside the TinyMCE-editor
- maybe an user didnt press the quote-button and just copy&paste the whole or parts of a post into the editor (in this case the quoted user is not contained inside the wrapper)

This means:

- Multiple different database-queries are required for selecting the content to cover (almost) all possible conditions (in worst case recursive queries to cover the copy&paste issue)
- This all should happen fast without reaching a maximum execution-time of PHP, what can be a big problem when there are dozens of posts/topics

**Comment by migulinek** [comment]
Asgaros must distinguish the username from plain text. Username in post, quotation or pasted text should be highlighted and tagged on the fly - to be active like on Facebook. The simple convention is for example start every nick / user from @. JavaScript can do it after quotation, paste or typing. Simply span element with class username. And if user remove his profile by BP, all references to his @username should be replaced by a @erased with link to nowhere, # in href. The same string without @ shouldn't be treated as a username, because on the bird forum you cannot replace all strings "eagle" into "deleted" only for the reason that some user had @eagle nick ;-)

**Comment by Asgaros** [comment]
A first version of BuddyPress Integration (no function included yet to delete personal data) can be found here:
https://www.asgaros.de/support/topic/buddypress-integration-v0-1/
