### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by Dtrieb** [Asgaros/asgaros-forum#227]
Hey I have the problem with the Font Awesome 4 (used by the Theme I used on the Website I admin)
The actual version of your forum use v5.

I read the https://www.asgaros.de/support/topic/loading-icons-conflicts-with-social-networking-buttons/
and try it but it didn't work for me.

Can you look at:
https://moschuss.de/forum/
Thanks!

**Comment by Asgaros** [comment]
Hello @Dtrieb 

Your site is looking fine for me. Can you post a screenshot of the problem? Also ensure, that the loading of the compatibility-library for FontAwesome is enabled in the settings.

**Comment by Dtrieb** [comment]
@asgaros

In deutsch weil es einfacher ist.
Ich habe unterschiedliche Symbole gehabt,
habe aber gerade gesehen das durchs Update alle auf fas fa-comments stehen.

**Comment by Asgaros** [comment]
@Dtrieb 

Ich gehe davon aus, dass du von einer Version < 1.14 geupdated hast. Mit Version 1.14 musste ich die verwendete Icon-Library wechseln, weshalb leider einmalig sämtliche Icons für die Foren neu gesetzt werden müssen. Dafür stehen dir nun allerdings eine vierstellige Auswahl an verschiedenen FontAwesome Icons zur Verfügung.

**Comment by Dtrieb** [comment]
Okay! Alles klar, danke.
