### ISSUE TITLE
Add Compatibility Layer for Toolset Views Content Templates

### ISSUE THREAD

**Issue by TukuToi** [Asgaros/asgaros-forum#228]
Hello, there - I'm working @[Toolset Support ](https://toolset.com/), where a common client/user reported that Asgaros' `forum` ShortCode will only fully work if inserted to a Post Body. 
This was confirmed as well by Plugin Supporters as a plugin's requirement (to insert the ShortCode in a Post Body), see [this discussion](https://wordpress.org/support/topic/forum-placed-with-shortcode-in-kadence-blocks-tab-loses-all-formatting/#post-11561249)

Toolset offers so-called Content Templates, think of them like Page Templates one can write for Themes in PHP, however, users can create these Content Templates without knowing a single line of PHP. Assigning such Content Templates (CT) to a post enables them to style the Post however they want with their Custom HTML and CSS.

CT's replace `the_content()` part of any post, hence CTs *can in fact display the `forum` shortcode*, but only if the Posts Body is displayed in such a CT.
If not, and the `forum` ShortCode is instead inserted *directly* into the CT (replacing the Post Body totally), then the Forum on the front end will miss scripts and styles.

As above shown in the discussions this is because Asgaros in that case doesn't load the scripts necessary.

A solution to this would be to add a Compatibility Layer to your Plugin, specifically after line 347 in `/asgaros-forum/includes/forum.php`, you could do something like this:
```
//Check if Toolset Views is active and if a CT is assigned to the Current Post
        if ( defined('WPV_VERSION') && ( (is_wpv_content_template_assigned($post->ID) == true) OR (get_post_meta($post->ID, '_views_template', true) > 0) ) ) { 

            //Get ID of CT assigned to the post
            $ct_id = get_post_meta($post->ID, '_views_template', true);

            //Get CT Contents
            $ct_content = get_post_field('post_content', $ct_id);

            //Check if there is "forum" shortcode in the CT
            $forum_in_ct = has_shortcode($ct_content, 'forum');

                //If there is "forum" shortCode, execute the Plugin
                if ($forum_in_ct == true) {
                    $this->executePlugin = true;
                }
        }
```

That would allow using the `forum` shortcode as well in a Content Template, instead of a Post Body only.

We don't see this as a BUG, our common users however might be confused about the current restriction, hence above integration could save some work :)

**Comment by Asgaros** [comment]
Hello @TukuToi 

Thank you for having a look into this issue! I just added your code with a few modifications to the development-version here on GitHub. It would be great if you could check out if everything is working well by downloading the following version of the plugin:

https://github.com/Asgaros/asgaros-forum/archive/ae39896bff228768fad4017fdb9850c8ca88eeb6.zip

Because your plugin is a premium-extension for WordPress which requires a license, I cannot test it by myself.

**Comment by TukuToi** [comment]
It results solved for me in the shared version - I also shared this with the common user of our plugins, you can see this thread here:
https://toolset.com/forums/topic/content-templates-do-not-properly-display-shortcode-from-asgaros-forum/

Thanks!
