### ISSUE TITLE
Signatur

### ISSUE THREAD

**Issue by BeG1990** [Asgaros/asgaros-forum#233]
Hi,
als erstes ein riesiges Dankeschön für diese tolle Forensoftware.
Ich habe das Problem, dass wenn ich einen Banner oder ähnliches in meine Signatur einbinde, diese rechtsbündig angezeigt wird. Besteht die Möglichkeit das zu ändern ? Habe schon mit versch. HTML Codes versucht aber leider ohne Erfolg. Habe die Codes natürlich vorher über die Signatureinstellungen freigegeben.
Würde mich riesig freuen wenn du da eine Idee hättest.

Danke und liebe Grüße,
Sören

**Comment by Asgaros** [comment]
Hallo @BeG1990 

Du kannst den folgenden Code unter Forum -> Appearance -> Custom CSS hinzufügen, um den Inhalt der Signatur zu zentrieren:

```
#af-wrapper .signature {
    text-align: center !important;
}
```

Bitte vergesse nicht, nach dem Speichern den Browser-Cache zu löschen, damit die Änderungen korrekt angezeigt werden.

**Comment by BeG1990** [comment]
Super, danke für die schnelle Antwort werde es gleich testen sobald ich Zuhause bin 👍
