### ISSUE TITLE
Breadcrumbs structured data issue

### ISSUE THREAD

**Issue by crizise** [Asgaros/asgaros-forum#234]
Hi!

We have been using Asgaros forum at several project for a while and everything was great.

However, recently we get an Breadcrumbs issues at Google Search Console. 
There two types of errors:
 
* Missing field "position"
 * Missing field "id"

Both errors related with [BreadcrumbList](https://schema.org/BreadcrumbList) 
First is for missed "position" field for "itemListElement": 
![image](https://user-images.githubusercontent.com/17177904/65411685-25f4bc00-ddf6-11e9-9879-eb920c56252d.png)
and the second pointed to _missing field id_ for "item":
![image](https://user-images.githubusercontent.com/17177904/65412600-3c037c00-ddf8-11e9-93e5-2ab20194c8ad.png)

Please, let us know how we can fix that.

Thanks!

**Comment by Asgaros** [comment]
Another issue-report regarding this:
https://www.asgaros.de/support/topic/google-search-console-reports-error/

I will try to take a look into this as soon as possible.

**Comment by Asgaros** [comment]
Hello @crizise 

Based on a status-update from Google there was an issue regarding the correct indexing of breadcrumbs. Please check out the following page for more details:
https://support.google.com/webmasters/answer/6211453#rich_result_reports

Can you confirm that the errors are becoming less in the recent days?

**Comment by Asgaros** [comment]
Fixed in the following commit:
https://github.com/Asgaros/asgaros-forum/commit/1d30942ae1ab214cc47853e88b44ea41cf7ed46d
