### ISSUE TITLE
Add the possibility to set a label/title to [spoiler] BBcodes

### ISSUE THREAD

**Issue by FlyThePlanet** [Asgaros/asgaros-forum#237]
The [spoiler] functionality is useful, but the way a spoiler is displayed in view mode in Asgaros is a bit too basic:
`+ Spoiler`

1/ The "Spoiler" word means nothing to everyone who doesn't speak English
2/ It does not announce what is in the spoiler

So I suggest to improve this BBcode by having the possibility to set a label/title to the [spoiler] BBcodes.
The parameter should be added the same way parameters are added to BBcodes like for [url=xxxxxx] or [quote=xxxxx]:
`[spoiler=Title]content[/spoiler]`
Which would be displayed in view mode:
`+ Title`

Here are some examples to demonstrate how useful it could be:
[spoiler=Click here to view the detail]Blah, blah, blah...[/spoiler]
`+ Click here to view the detail`

[spoiler=Klicken Sie hier, um das Detail anzuzeigen]Blah, blah, blah...[/spoiler]
`+ Klicken Sie hier, um das Detail anzuzeigen`

[spoiler=Procedure for Gmail]Blah, blah, blah...[/spoiler]
[spoiler=Procedure for Hotmail]Blah, blah, blah...[/spoiler]
`+ Procedure for Gmail`
`+ Procedure for Hotmail`

At last, of course, like for other BBcodes, this parameter should stay optional.

**Comment by Asgaros** [comment]
A new title-attribute will be available for the spoiler-shortcode with the next update:

`[spoiler title="View Details"]My Content ...[/spoiler]`
