### ISSUE TITLE
Jump to top

### ISSUE THREAD

**Issue by ghost** [Asgaros/asgaros-forum#239]
Hi,
It would be great if there was the Jump to top feature under every thread. To the right of the thread number.

Thanks
Stefan

**Comment by Asgaros** [comment]
Thank you for your suggestion!

Implementing such a functionality directly inside of the forum is not the right place. Instead, such a functionality should be part of the theme so it allows users to scroll to the top on every kind of page - not only inside of the forum. Adding this functionality to the forum only also comes with the risk that an existing scroll-up button added by the theme is duplicated or covered.
