### ISSUE TITLE
Russian language interface

### ISSUE THREAD

**Issue by DS455** [Asgaros/asgaros-forum#240]
Hi, I installed the forum plugin, but I can’t find the choice of the interface language, how can I change the interface language to Russian? Thanks.

**Comment by Asgaros** [comment]
Hello @DS455 

You can change the language in your general WordPress-settings. Dont forget to update your language-files via the Dashboard.

**Comment by DS455** [comment]
Thank you, I solved the problem, I had the wrong permissions on the /var/www/wp-content/language directory.
