### ISSUE TITLE
Forum profile with wpautop formatting

### ISSUE THREAD

**Issue by trebitzki** [Asgaros/asgaros-forum#241]
The user profile page is not formatted for line breaks and paragraphs. Users (like me) who want to have their text in a nicely readable form are left out. The solution is quite simple:

In the file plugins/asgaros-forum/includes/forum-profile.php around line 270 the statement

$cellValue = trim(esc_html($userData->description));

can be changed to

$cellValue = trim(wpautop(esc_html($userData->description))); // << add this

The change would not cause havoc with existing profiles nor introduce any security issues. I urge you to implement this in the next incremental version. Thanks!!

**Comment by Asgaros** [comment]
Hi @trebitzki 

Thanks for your suggestion! I implemented it in the current development-version and it will be available with the next update.
