### ISSUE TITLE
Russian translate

### ISSUE THREAD

**Issue by ironboys** [Asgaros/asgaros-forum#25]
I found couple of mistakes in the translation. Has to translate the word submit as to Отправить and there to Удалить сообщение. And the word view has to translates as Просмотры and there  Представления

**Comment by Asgaros** [comment]
Can you please update the strings at the WordPress page?

https://translate.wordpress.org/locale/ru/default/wp-plugins/asgaros-forum

**Comment by ironboys** [comment]
I corrected. There were already approved words which someone already before my translation made. I too didn't check the already translated

**Comment by Asgaros** [comment]
Alright. I updated the strings and include them in the next release. :)

**Comment by ironboys** [comment]
It is possible I will receive corrections now?

**Comment by Asgaros** [comment]
You have to replace the files in your plugin /languages folder.

[languages.zip](https://github.com/Asgaros/asgaros-forum/files/86144/languages.zip)

**Comment by ironboys** [comment]
Thank you
