### ISSUE TITLE
Show group-titles on mobile-view

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#253]
Show group-titles on mobile-view

**Comment by fanSte1986** [comment]
Hi, im also looking for this feature. Its allready 2 years in your bug-list and never released into a new update.

Are you planning to fix it soon?

Usergroups are important in my forums, so i really hope to see it on mobile too...

Thank you.

**Comment by Asgaros** [comment]
Hello @fanSte1986 

This will be fixed with the upcoming update.
