### ISSUE TITLE
Mobile version improvements

### ISSUE THREAD

**Issue by ironboys** [Asgaros/asgaros-forum#26]
About mobile version. It is advisable to add quantity of posts in a conclusion of forums and subjects on the right.
To add an avatar of the author and date of writing of the message in subjects.

**Comment by Asgaros** [comment]
Yes, it is possible. But I have to work on a good layout first. I am not sure yet when it will be released.

**Comment by ironboys** [comment]
Well I on the future. And that looks too simply. The subject conclusion in previous more was pleasant to the version. Thanks

**Comment by Asgaros** [comment]
I just made some improvements to it which were added to the dev-version of the plugin. The mobile-styles adapt now better to the screen-wide and shows more information as long as there is enough space.
