### ISSUE TITLE
Available hooks

### ISSUE THREAD

**Issue by gitgrupoift** [Asgaros/asgaros-forum#271]
I already made use of a number of actions and filters I found within the code, but perhaps a reference would be nice.

**Comment by qualmy91** [comment]
Hey @gitgrupoift, 

at the moment there is an overview of all available hooks in the [support forum](https://www.asgaros.de/support/topic/list-of-available-hooks-and-filters/).

And I already started with a documentation for the [available hooks](https://github.com/Asgaros/asgaros-forum/blob/master/hooks.md). You are welcome to add some new filters in this file to help other users.

**Comment by Asgaros** [comment]
Hey @gitgrupoift 

Thanks for your feedback. We will work on that in a separate ticket which you can find here: #276
