### ISSUE TITLE
Make login-notifications clickable

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#279]
Reference:
https://www.asgaros.de/support/topic/register-log-in-display-mobile-view/#postid-11735

**Comment by qualmy91** [comment]
What do you think about to always show a link to the login page or login and register page? Like:


You need to log in to create posts and topics.

- login
- register

**Comment by qualmy91** [comment]
@Asgaros 

Can you please assign me to this issue
