### ISSUE TITLE
Wordpress post comment system

### ISSUE THREAD

**Issue by XeonG** [Asgaros/asgaros-forum#285]
Possible to have wordpress posts that get posted to certain forum sections, and the comment system on those posts is the same as the forum replies to that topic?

It's a very useful integration for the community, would be nice to see.

**Comment by Asgaros** [comment]
I don't have any plans to add this feature because this plugin will focus to add a forum-functionality to WordPress instead of being a replacement for the WordPress comments section.

**Comment by XeonG** [comment]
yeah but many sites that have news announcements will have the post in the forum, and then you've got people commeting on a news topic as wordpress comments, and then in the forum the same news topic will have forum replies.. its just silly that way. Seen many integrations with forum software like xenforo, smf, vbulletin, all have this kind of integration so that there isn't this 2 seperate comment systems going on for the same topics that are shown on frontpage/portal and forum etc.

**Comment by Asgaros** [comment]
Yes, I understand the concern. An option would be to just disable the built-in comment functionality of WordPress and add a template-section in your news-template with a Call-To-Action which leads to the corresponding forum-topic. As an alternative, the [forum topic="123"] shortcode could be added automatically to the end of your post to show the topic-view there. Both solutions would require a bit of custom-development of course.
