### ISSUE TITLE
Some icons in the theme will be incompatible after opening the forum plugin

### ISSUE THREAD

**Issue by chuiyukong** [Asgaros/asgaros-forum#299]
Hello bro,
When I turned on the forum plug-in, some icons in the theme became squares.
like this:
![image](https://user-images.githubusercontent.com/40864044/101012824-57dae400-359e-11eb-8b24-2f8ee20ca533.png)
it became this:
![image](https://user-images.githubusercontent.com/40864044/101012936-83f66500-359e-11eb-80b4-42545d7f0ce5.png)
It is the same in other places.

**Comment by Asgaros** [comment]
Hello @chuiyukong 

Can you let me know which theme you are using? Have you played around with the FontAwesome-options in Forum -> Settings -> Features?

**Comment by chuiyukong** [comment]
Thank you,I found that I turned on the Load Font Awesome v4 compatibility library button before, and the problem was solved when I turned it off.
