### ISSUE TITLE
Add lightbox to images

### ISSUE THREAD

**Issue by qualmy91** [Asgaros/asgaros-forum#303]
https://www.asgaros.de/support/topic/image-lighbox/

**Comment by gevv** [comment]
system fast and stable  asgaros very good

must have add-on for new features

don't let the core change

(_in my opinion)_

**Comment by Asgaros** [comment]
Basically its a nice idea. However, I think lightbox-functionality is more related to the used theme or as a standalone-extension which adds this functionality to all images on the website - not only to the ones used in the forum. To avoid overhead, compatibility-issues and to prevent the case that multiple lightbox-libraries are used on a website, I am currently avoid adding this functionality. However, maybe I will change my mind in the future. :-)
