### ISSUE TITLE
Option to remove the default forum menu

### ISSUE THREAD

**Issue by Mastergmes2106** [Asgaros/asgaros-forum#310]
Only a function in the form of a box on appearance or so to hide the menu.

**Comment by qualmy91** [comment]
This functionality will be available in [Toolbox for Asgaros Forum](https://wordpress.org/plugins/toolbox-for-asgaros-forum/) whenever #286 will be pulled to the code.

**Comment by Asgaros** [comment]
Added _asgarosforum_filter_show_header_ filter for this in #286.
