### ISSUE TITLE
Bug: Rank Math

### ISSUE THREAD

**Issue by qualmy91** [Asgaros/asgaros-forum#315]
It seems like Rank Math is causing an error  while removing Asgaros Forum:
https://wordpress.org/support/topic/cant-delete-this-plugin-8/#post-13989339

**Comment by Asgaros** [comment]
Hey @qualmy91 

Is this bug already fixed with one of the latest Rank Math updates or is this problem still there?

**Comment by qualmy91** [comment]
Hey Thomas, 

I didn't check it yet. This was just reported by a user.
