### ISSUE TITLE
Add compatibility with Social Sharing Plugin – Sassy Social Share

### ISSUE THREAD

**Issue by qualmy91** [Asgaros/asgaros-forum#325]
Topic: https://www.asgaros.de/support/topic/hi-when-i-share-on-social-topic-title-and-image-not-shown/

@Asgaros  Should we add the following code to Asgaros Forum? It will pass the right URL to Sassy Social Share if it's a forum or topic view. If yes, should I add it to /integrations or do you want it to another location?

```
add_filter('heateor_sss_target_share_url_filter', 'adjust_forum_url');

function adjust_forum_url ($post_url){
    global $asgarosforum;
    $forum_id = $asgarosforum->current_forum;
    $topic_id = $asgarosforum->current_topic;
    if ($forum_id && $topic_id){
        $post_url = $asgarosforum->rewrite->get_link('topic', $topic_id);
    } else if ($forum_id){
        $post_url = $asgarosforum->rewrite->get_link('forum', $forum_id);
    }
    return $post_url;
}
```

**Comment by Asgaros** [comment]
Hello @qualmy91 

I think we can add this to the compatibility-file.

**Comment by qualmy91** [comment]
@Asgaros 

Ok, just assign me to this issue. I will add this the next days
