### ISSUE TITLE
Mobile thread

### ISSUE THREAD

**Issue by ironboys** [Asgaros/asgaros-forum#35]
It is possible to draw a conclusion of subjects on mobile version here such look http://prntscr.com/9qqcot . Conveniently and habitually

**Comment by Asgaros** [comment]
What exactly do you mean? Can you go in detail?

**Comment by ironboys** [comment]
Akavtarka conclusion at the left, nearby on the right a nickname of the author and in the bottom of a nickname date of the publication of the message.

**Comment by Asgaros** [comment]
Yeah, lets discuss the mobile improvement stuff in the existing ticket here:
https://github.com/Asgaros/asgaros-forum/issues/26
