### ISSUE TITLE
Is Asgaros an abandoned project?

### ISSUE THREAD

**Issue by sks-zigzag** [Asgaros/asgaros-forum#357]
Is Asgaros Forum & support is abandoned? No replies since last year? Even tried to use the support forum on the site and there is no way to retrieve the account to post anything as it doesn't appear to be sending any emails when requesting forgotten password or creating an account. Tried both. Different email, tried different email host, checked spam. Nothing.

I know it's a free plug in and I would gladly pay for support if you would allow it, but no way to contact email support either.

**Comment by FlyThePlanet** [comment]
No it's not abandoned. Thomas released again today a new version...
https://www.asgaros.de/support/forum/announcements/

But as far as I understand, he was student when he developed Asgaros, so he could afford to spend a lot of time on this project. However in 2019 he graduated, he's now working and his private life has probably evolved, so he probably now have little time to dedicate to Asgaros, especially to answer questions one by one...
https://www.linkedin.com/in/thomasbelser/

So it's moving, but slower than before.
