### ISSUE TITLE
HTML in forum descriptions not working anymore, probably since version 2.0.0

### ISSUE THREAD

**Issue by FlyThePlanet** [Asgaros/asgaros-forum#358]
The possibility to add HTML code in the forum descriptions was officially added in version 1.9.1 in June 2018...

> **1.9.1**
> - Fixed: Broken usernames when URL contains certain special characters
> - Fixed: Broken profile URLs when usernames are numeric
> - Fixed: Broken URLs when using certain custom permalink structures
> - Fixed: Dont show last seen-status in profiles/memberslist when who is online-functionality is disabled
> - **Changed: Allow HTML in forum descriptions**
> - Added: asgarosforum_widget_recent_posts_custom_content hook
> - Added: asgarosforum_widget_recent_topics_custom_content hook

It worked perfectly fine for 4 years, but it's not the case anymore, probably since version 2.0.0...
https://www.asgaros.de/support/topic/forum-description-not-interpreting-html/#postid-38552

- If the HTML code was already in the forum description, the code is now displayed as text in the middle of the description
- And if we try to edit a forum description and add some new HTML code, the code is now automatically removed when we save the forum settings form.

So could it be possible to fix the issue?
It's very useful to be able to add carriage returns, bold/color/underline, URLs or FA icons to forum descriptions.

Thanks!

**Comment by Asgaros** [comment]
Hello @FlyThePlanet 

I got forced by the WordPress Security Team to implement those restrictions. It is NOT allowed anymore to give users the ability to inject Scripts/HTML/etc directly within inputs by user. I know it doesnt make any sense since the user in that case is an admin, but the consequence would have been a delisting from the plugin repository.
