### ISSUE TITLE
wrong output data in version 2.2.1

### ISSUE THREAD

**Issue by seema84** [Asgaros/asgaros-forum#359]
The latest Version (https://github.com/Asgaros/asgaros-forum/commit/e5f535dce86cd955b80cbda940b558d9a2879584) break my widget design.
Here the CSS class style-block is missing and has been replaced by style-widget.

**Comment by Asgaros** [comment]
Hello @seema84 

Can you provide a screenshot with an example?

**Comment by seema84** [comment]
before the update

![12](https://user-images.githubusercontent.com/2832339/222432930-d4851edb-55b0-4b2c-a06a-9ddca9dd16bf.PNG)
![12c](https://user-images.githubusercontent.com/2832339/222432937-bdac2551-4fec-490f-ac03-b4927e0647da.PNG)

after this update

![13](https://user-images.githubusercontent.com/2832339/222433034-ae295c96-c8cf-4dfa-9ac4-9cd23948109e.PNG)
![13c](https://user-images.githubusercontent.com/2832339/222433044-1152893d-baff-4b94-9928-7d55649d8266.PNG)

hope this helps (i also tried to write to you on fb so i could explain this better, but you don't seem to be really active there anymore :D)

I have temporarily fixed it like this:

        echo wp_kses_post($args['before_widget']);
        echo wp_kses_post($args['before_title']);
        echo esc_html($title);
        echo wp_kses_post($args['after_title']);
        echo wp_kses_post($output);
        echo wp_kses_post($args['after_widget']);

to

        echo $args['before_widget'];
        echo $args['before_title'];
        echo $title;
        echo $args['after_title'];
        echo $output;
        echo $args['after_widget'];

in widget-recent-posts.php and widget-recent-topics.php

However, I am sure that this cannot be a permanent solution.

**Comment by Asgaros** [comment]
Thanks, I will have a look into that.

The shown changes got applied due to a security audit by the WordPress team. I know they mostly doesnt make any sense at that point but I risked a de-listening from the plugin repository otherwise. I will check what I can do and keep you updated here.

And sorry for the delay in response. I am currently in Shanghai and thats one of the reasons why Facebook is not my main communication channel anymore. :)

**Comment by Asgaros** [comment]
Will revert that special escaping in the next version. WordPress Core is not even doing it by themselves and the documentation suggests doing it in the same way:
https://developer.wordpress.org/themes/functionality/widgets/#sample-widget

**Comment by seema84** [comment]
Thank you very much. I have already seen that you are in Shanghai. I hope you have a good time.
