### ISSUE TITLE
Getting ###FORUM### to work in subject of notifications

### ISSUE THREAD

**Issue by glorious1** [Asgaros/asgaros-forum#361]
Thomas, you asked me to create an issue about this.  ###FORUM### works in the email body, but not the subject line.  The relevant support forum thread is:
https://www.asgaros.de/support/topic/include-forum-name-in-notifications/

and the pull request that I did (leaving out this feature) was https://github.com/Asgaros/asgaros-forum/pull/346

Is it as simple as adding the commented line to this section of `forum_notifications.php`?
**forum_notifications.php, starting line 209**

        // Prepare subject.
        $notification_subject = $this->asgarosforum->options['mail_template_new_post_subject'];
        $notification_subject = str_replace('###TITLE###', wp_specialchars_decode($topic_name, ENT_QUOTES), $notification_subject);
     // $notification_subject = str_replace('###FORUM###', wp_specialchars_decode($forum_name, ENT_QUOTES), $notification_subject);

        // Prepare message-content.
        $message_content = wpautop(stripslashes($post->text));
        $message_content .= $this->asgarosforum->uploads->show_uploaded_files($post->id, $post->uploads);

        // Prepare message-template.
        $replacements = array(
            '###AUTHOR###'  => $author_name,
            '###LINK###'    => '<a href="'.$post_link.'">'.$post_link.'</a>',
            '###TITLE###'   => $topic_name,
            '###FORUM###'   => $forum_name,
            '###CONTENT###' => $message_content
        );
Not sure if anything is needed in `forum.php`.

**Comment by Asgaros** [comment]
This enhancement will be included with the upcoming update. Thank you for this suggestion!
