### ISSUE TITLE
Allow users to delete their own topics, but only if no replies

### ISSUE THREAD

**Issue by peoyli** [Asgaros/asgaros-forum#362]
I'm trying to implement a protection against deletion of a topic by its owner if it contain replies.
If the topic is only containing posts by the owner, then it should be ok to delete.

I guess the correct way to add the feature is to use the hook "asgarosforum_before_delete_topic", but as I cannot get it working by directly modifying the forum.php file, it would not work the correct way either..

Non-working code added to forum.php (it also prevents deletion of a topic without replies),added just below the "do_action" for the mentioned hook:
(code block does not work)
---
        // Continue ...
        do_action('asgarosforum_before_delete_topic', $topic_id);

        // Delete posts.
        $posts = $this->db->get_col($this->db->prepare("SELECT id FROM {$this->tables->posts} WHERE parent_id = %d;", $topic_id));
// PeO mod here //
$_peo_post_count=0;
        foreach ($posts as $post) {
          $_peo_post_count++;
        }
if ($_peo_post_count != 0) {
  return false;
}
// End PeO //
        foreach ($posts as $post) {
            $this->remove_post($post, false);
---

I have also tested with count($posts) with the same result.

**Comment by peoyli** [comment]
No, I didn't style it that way :)

**Comment by Asgaros** [comment]
Hello @peoyli 

The next release will include a new option which allows users to only delete their own topics if it has no replies.

Thank you for your suggestion!
