### ISSUE TITLE
Can't post new threads or topics

### ISSUE THREAD

**Issue by HansOffice** [Asgaros/asgaros-forum#363]
I'm using this plugin for the first time, the configuration I've got it all worked out but I can't seem to find the ability to post. Clicking on the forum I made automatically refreshes the page and does not go inside the forum, is there something wrong with my settings somewhere?
![屏幕截图(5)](https://user-images.githubusercontent.com/94523696/210769283-cf1a8d82-a434-428a-8804-16400fecea96.png)

**Comment by Asgaros** [comment]
Hello @HansOffice 

This looks for me like a cache issue or an incompatibility with another plugin/theme. Please disable for testing purposes other plugins to see which one is causing this issue.
