### ISSUE TITLE
Suggestion: option for title_length (widget)

### ISSUE THREAD

**Issue by seema84** [Asgaros/asgaros-forum#367]
It would be nice if you could define the title_length yourself (default is 33).
https://github.com/Asgaros/asgaros-forum/blob/bc6381a7d12c150a056c306f6fd2a60f8aa6060f/widgets/widget-recent-posts.php

**Comment by Asgaros** [comment]
Hello @seema84 

You can change the length of the widget-titles via the _asgarosforum_filter_widget_title_length_-filter.

Here is an example-code which you can add to your themes _functions.php_-file:

```php
add_filter('asgarosforum_filter_widget_title_length', 'custom_widget_length');

function custom_widget_length($length) {
    return 50;
}
```

**Comment by seema84** [comment]
thanks <3
