### ISSUE TITLE
after install build 2.7.0 plugin not started

### ISSUE THREAD

**Issue by chocholousek** [Asgaros/asgaros-forum#372]
`Got error 'PHP message: PHP Parse error:  syntax error, unexpected ')' in /data/web/ted/web/wp-content/plugins/asgaros-forum/includes/forum-compatibility.php on line 194\n'`

**Comment by Asgaros** [comment]
Hello @chocholousek 

This sounds like the file is corrupt and maybe not get updated correctly. Can you try to re-upload it (do NOT uninstall the plugin because it removes all data as well).

**Comment by chocholousek** [comment]
I reinstalled the plugin 3 times, once manually copied using ftp. Always the same result. Editing forum-compatibility.php on line 193 helped.

       $usergroup_term_ids = get_terms(
            array(
                'taxonomy'   => 'asgarosforum-usergroup',
                'fields'     => 'ids',
                'hide_empty' => false,
            )
        );

**Comment by Asgaros** [comment]
Ooops, I see the issue now. I will fix it with the next update as well!
