### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by ironboys** [Asgaros/asgaros-forum#38]
It is possible to make function of ranks and awards at a forum. For example I have a sports site, wanted to encourage active with some ranks and awards. And that the rank was removed under a nickname in a forum, will to allocate the active so easier. It is also necessary to make that when pressing a nickname the questionnaire with data on the author, with awards and ranks was output

**Comment by Asgaros** [comment]
No, it is nothing which should be in the core system. Maybe it is a feature someone can develop as a plugin for Asgaros Forum.
