### ISSUE TITLE
Improvements for Last posts-Widget

### ISSUE THREAD

**Issue by ironboys** [Asgaros/asgaros-forum#39]
According to users of the site the widget of the last subjects of a forum looks ugly and therefore the forum doesn't attract people. More conveniently it will also be beautiful here such option, which on a screenshot  http://prntscr.com/9vgv4rThere is an option to make such widget?

**Comment by Asgaros** [comment]
You can style the widget via CSS so it fit your needs. Changes to the widgets are not planned yet. Maybe I will add some hooks to it so you can add additional functionality like avatars by yourself.

**Comment by ironboys** [comment]
Yes it would be good if write as to remove in a widget of avatars of the author, the counter of answers in a subject and the counter of viewings of a subject. Further itself would adjust

**Comment by Zmajur** [comment]
Its Possible to limit character words in title? Good for footer widget. Now one thread title splits on two rows...

**Comment by Asgaros** [comment]
Yes, it should be possible to modify it via some filters. I will check it out and try to add something so you can modify the amount of characters for titles.

**Comment by Asgaros** [comment]
Reference for myself: Example on how to add avatars to the widget:
https://wordpress.org/support/topic/the-idea-of-to-widget?replies=2#post-8544675
