### ISSUE TITLE
Require login

### ISSUE THREAD

**Issue by ironboys** [Asgaros/asgaros-forum#40]
There was a problem, wanted to open a forum for guests as it was closed but at the instruction before require_login and false and true the forum doesn't open. Whether there will be in the following release an opportunity to open and close a forum for guests with the administrator of the panel or prompt as to open a forum for guests

**Comment by Asgaros** [comment]
There is already a Issue-report for this here:
https://github.com/Asgaros/asgaros-forum/issues/20

It is not possible to create posts/topics for guests yet. The require_login option is available to define if a forum is visible to everyone or for logged in users only.

**Comment by ironboys** [comment]
PROMT
It is necessary for me that guests could read a forum and subjects. For some reason demands authorization to read a subject for guests

**Comment by Asgaros** [comment]
Disable the require_login option and it will be visible.

**Comment by ironboys** [comment]
Require login is switched off having specified false or true? Having specified also false and true the forum didn't open

**Comment by Asgaros** [comment]
Can you see the forum when Require_login is switched off?

**Comment by ironboys** [comment]
No. For some reason at inclusion and switching off of require login writes Sorry, to only logged in users have access to the forum." Login

**Comment by Asgaros** [comment]
Strange. Do you use some caching plugin?

**Comment by ironboys** [comment]
Yes. Cash cleaned. I initially there have false but a forum was all the same closed

**Comment by Asgaros** [comment]
Can you make Screenshots of your Forum settings page and the page where the error appears (included the URL).

**Comment by ironboys** [comment]
and the forum opened. Thanks for the help

**Comment by ironboys** [comment]
At last I corrected. Few times I cleared chache and the forum opened. Thanks you
