### ISSUE TITLE
Adding a Rich Text Editor

### ISSUE THREAD

**Issue by CoolClownFish** [Asgaros/asgaros-forum#43]
Is there a way to add a rich text editor to the forums?

**Comment by Asgaros** [comment]
There is already by a rich-editor, see this screenshot:
https://ps.w.org/asgaros-forum/assets/screenshot-4.png

Is it not working for you?

**Comment by CoolClownFish** [comment]
I'm sorry Asgaros, It is working but I just realized only when I am on a normal internet connection. If I am teathered through my phone at work or somewhere it don't show up however this is only when I am using Foxfi to teather my android to my laptop.

**Comment by Asgaros** [comment]
No problem! Thanks for your reply. :)
