### ISSUE TITLE
Forum Search Bar code

### ISSUE THREAD

**Issue by CoolClownFish** [Asgaros/asgaros-forum#45]
Hey there. I am running a theme for my site from appthemes that don't include forum posts in the search. I would like to have a separate search for the forums if possible. Is there a way to add a Forum Search above the Forums? The  theme I use is for a classifieds site. www.utahreefswap.com

**Comment by Asgaros** [comment]
Hey,

it is not possible yet to search for forum posts. But it is planned for a future version, see this ticket:
https://github.com/Asgaros/asgaros-forum/issues/7

**Comment by CoolClownFish** [comment]
Asgaros, I seen that. I was wondering about a separate search bar just for the forums. My site is mainly for classifieds and I would like to keep the searches separate. Is that what you are planning on or just using the standard site search?

**Comment by Asgaros** [comment]
Oh, I see. I think it will be separated from the default search. But I will try to use some of the existing WordPress searching functionalitys/APIs so it will be better integrated than when I write my own search functionality from scratch.
