### ISSUE TITLE
Title pages

### ISSUE THREAD

**Issue by ironboys** [Asgaros/asgaros-forum#46]
t would be good for seo if names thread that went to title pages. And that title remain empty in any subject and at a forum

**Comment by Asgaros** [comment]
Can you give me some examples? The title of threads and forums are added to the <title> attributes.

**Comment by ironboys** [comment]
For example I have a subject with the name What sport you are engaged. Upon transition to a subject to title it is specified only the name of the site, respectively and from searchers inquiries on title of a subject won't be

**Comment by Asgaros** [comment]
You mean the title of your browser window (html title-tag) or some title on your website?

**Comment by ironboys** [comment]
title of  browser window (html title-tag)

**Comment by Asgaros** [comment]
On my local installation the html title-tag is changed to the subject of the forum, see:
http://fs5.directupload.net/images/160214/8xce5gqx.png

Maybe another plugin is overriding it?

**Comment by ironboys** [comment]
You established some plug-in for title? At me forum site everywhere in subjects is simple

**Comment by Asgaros** [comment]
No, the forum changes the page title. But if you cant see it, some of your other plugins or themes modifies it.

**Comment by Asgaros** [comment]
Can you check if the titles are working when you change:
`add_filter('wp_title', array($this, 'get_pagetitle'), 10, 3);`
to
`add_filter('wp_title', array($this, 'get_pagetitle'), 9999, 3);`
_in includes/forum.php?_
