### ISSUE TITLE
Shortcodes for categories/forums/threads

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#47]
Add shortcodes for:
- Categories
- Forums
- Threads

References:
https://wordpress.org/support/topic/more-to-the-shortcode?replies=3
https://wordpress.org/support/topic/select-categoriesforum?replies=2
https://wordpress.org/support/topic/specific-forum-category?replies=1
https://wordpress.org/support/topic/shortcode-forum-id-for-specific-page/

**Comment by andreiclep** [comment]
Hello. 
I really enjoy the plugin, but we need more instances of it to work for our needs.
Are you still working on "different forum instances" ?

Thanks.

**Comment by Asgaros** [comment]
Hello @andreiclep 

Please check the following topic to show specific forum instances only:
https://www.asgaros.de/support/?view=thread&id=45
