### ISSUE TITLE
Subforums

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#48]
Add subforum functionality.

**Comment by multirotor-ovh** [comment]
Please consider changing this to a higher priority, it is a most useful option and is making me reconsider using Asgaros Forum on my site which would be a shame.
Greg, https://multirotor.ovh

**Comment by Asgaros** [comment]
Hey! Yes, I think this is one of the features which should come next.

**Comment by Asgaros** [comment]
First draft of the forum overview including subforums.

![subforums1](https://cloud.githubusercontent.com/assets/12525671/14234682/18f04820-f9e9-11e5-9a92-9dc478d14c1b.PNG)

**Comment by multirotor-ovh** [comment]
You are a star :)
Greg

**Comment by multirotor-ovh** [comment]
So currently I should create a subforum as a forum and manually change the parent_forum database field until you make the required changes in admin/admin.php:add_category_form_fields and edit_category_form_fields?
Not a problem, what you have already done has saved me a load of work :+1:

**Comment by Asgaros** [comment]
No, I have to make sure that the forum-stats are calculated correctly. The page-navigation is also not complete and the subforums should be viewable inside the parent-forum.

Another problem for now: If you make changes to the forum in the administration area, the subforums get deleted from the database. So please dont change anything inside your database for now! :bomb:

**Comment by Asgaros** [comment]
The frontend should be ready for subforums now.

Next step will be the backend:
- [ ] Create subforums
- [ ] Delete subforums when deleting parent forums

**Comment by Asgaros** [comment]
Hello @multirotor-ovh 

With the last commit I added sub-forums management to the backend. Testing and feedback is highly appreciated.

**Comment by Asgaros** [comment]
![test](https://cloud.githubusercontent.com/assets/12525671/14588407/6271a738-04c9-11e6-8b1d-2c406ec35216.PNG)

**Comment by DimitrisHD** [comment]
is this ready to use?

**Comment by Asgaros** [comment]
It should be relatively stable now. Maybe I have to tweak and fix some things, but I dont expect breaking changes so hopefully I can release it as a stable-version soon.

**Comment by sc4t** [comment]
Yes it is well configured
