### ISSUE TITLE
Approve Topics

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#49]
Add a functionality to approve topics.

Current to-do list:
- [x] Prepare database
- [x] Add forum-option to enable/disable approval-functionality
- [x] Add logic for new topics so they are (un-)approved after creation
- [x] Add logic to approve a topic for moderators/administrators
- [x] Add special styling in front-end for un-approved topics
- [x] Add notification when there is a new un-approved topic
- [x] Add an option to define which users topics need approval (guests, normal)
- [x] Ensure that topics from moderators/administrators dont need approval
- [x] Ensure that unapproved topics dont appear in topic-list and other areas (widgets, notifications, last-post, activity, unread, etc)
- [x] Prevent access to unapproved topics via URL-manipulation
- [x] Approve all topics when disabling the approval-option for a forum
- [x] Ensure that nobody can answer or moderate in unapproved topics
- [x] Notify subscribers/mentioned-users when a topic got approved
- [x] Ensure that no notifications/mentions are sent for unapproved topics
- [x] Notify topic-creator that his topic requires approval
- [x] Add a frontend-view for unapproved topics
- [x] Ensure that only moderators/administrators have access to the frontend-view
- [x] Ensure that we cannot subscribe to unapproved topics
- [x] Redirect users to the overview when they try to access an unapproved topic (also for rss-feed)
- [x] Ensure that moderators can only see accessible unapproved topics
- [x] Ensure approval also works with shortcode-parameters
- [x] Show approval-notice for moderators only in the overview

**Comment by norrest** [comment]
Thank you!

**Comment by sonicbobcat85** [comment]
I'd like to bump this. This is a requirement for our community. Ideally, we'd also like to specify a list of rules and/or keywords that would cause a post to be held in moderation (on suspicion of content impropriety, spam, etc.), else publish it immediately.

**Comment by AME-Network** [comment]
Agreed. Way overdue, we will definitely **donate** towards a confirmed eta of this critical feature!

**Comment by Asgaros** [comment]
Hello everyone,

my current plan is to add this feature in the upcoming v1.13 release. I want to get some feedback about the possible implementation:

- Enable approval globally or for specific forums only?
- Approval for topics or also for posts? Which one is more important?
- I want to add an option to define globally for which users approval is needed: Guests or/and Normal Users
- Moderators/Administrators should be excluded from approval, right?
- Have moderators access to unapproved topics or only administrators?
- Any rules to make approval not necessary for certain users? For example: If a user has X approved topics or posts?

**Comment by AME-Network** [comment]
ANSWERING INLINE: 

On 2018-12-02 14:12, Thomas wrote:

> Hello everyone, 
> 
> my current plan is to add this feature in the upcoming v1.13 release. I want to get some feedback about the possible implementation: 
> 
> * Enable approval globally or for specific forums only? - GLOBAL
> * Approval for topics or also for posts? Which one is more important? - BOTH
> * I want to add an option to define globally for which users approval is needed: Guests or/and Normal Users - BOTH
> * Moderators/Administrators should be excluded from approval, right? - YES
> * Have moderators access to unapproved topics or only administrators? - ADMIN
> * Any rules to make approval not necessary for certain users? For example: If a user has X approved topics or posts? - NO
> 
> THANK YOU THOMAS!! 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/Asgaros/asgaros-forum/issues/49#issuecomment-443547118
[2]

**Comment by Asgaros** [comment]
Thank you for your feedback. I have official started to work on this now and you can monitor the progress in the first post. As you see this requires a lot of under-the-hood changes so I keep this functionality in the beginning as simple as possible:

- it will be possible to define approval-status for individual forums
- in the beginning only topic-approval will be possible (post-approval will come in a future release)
- topics will be approved via the frontend
- moderators/administrators will be able to approve topics because both of them have full frontend-rights
- no approval needed for topics made by moderators/administrators
- the site-owner will get notified for new unapproved-topics

**Comment by AME-Network** [comment]
Great. Looking forward the post-approval addition, which I believe is
just as important. One idiot can screw up an entire thread. Will donate.
Thanks. 

-- 

On 2018-12-05 10:35, Thomas wrote:

> Thank you for your feedback. I have official started to work on this now and you can monitor the progress in the first post. As you see this requires a lot of under-the-hood changes so I keep this functionality in the beginning as simple as possible: 
> 
> * it will be possible to define approval-status for individual forums
> * in the beginning only topic-approval will be possible (post-approval will come in a future release)
> * topics will be approved via the frontend
> * moderators/administrators will be able to approve topics because both of them have full frontend-rights
> * no approval needed for topics made by moderators/administrators
> * the site-owner will get notified for new unapproved-topics
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/Asgaros/asgaros-forum/issues/49#issuecomment-444593585
[2]

**Comment by Asgaros** [comment]
I think the first version of the approval-feature for new topics is ready for testing. As you can see in this ticket this feature is very complex and requires dozens of changes inside the code - new logic as well as modifications to existing functionality. This brings the risk for bugs.

If you want help to test this new feature you can download a stable development-version via this link:
https://github.com/Asgaros/asgaros-forum/archive/8f731309f843afcbe43414ddee2bec3ad80949ab.zip

**Comment by AME-Network** [comment]
Great! When the bugs are ironed out and the update is available via WP
Repository, we'll update and donate. 

Cheers! 

-The AME Team 

-- 

On 2019-01-04 14:37, Thomas wrote:

> I think the first version of the approval-feature for new topics is ready for testing. As you can see in this ticket this feature is very complex and requires dozens of changes inside the code - new logic as well as modifications to existing functionality. This brings the risk for bugs. 
> 
> If you want help to test this new feature you can download a stable development-version via this link:
> https://github.com/Asgaros/asgaros-forum/archive/8f731309f843afcbe43414ddee2bec3ad80949ab.zip 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/Asgaros/asgaros-forum/issues/49#issuecomment-451589695
[2]
