### ISSUE TITLE
Reply at the same page

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#53]
Reply at the same page.

See:
https://wordpress.org/support/topic/reply-on-same-page?replies=2#post-8059914
https://wordpress.org/support/topic/view-post-that-you-are-replying-to?replies=1
https://wordpress.org/support/topic/reply-box-below-the-threads?replies=1
https://wordpress.org/support/topic/the-form-of-response-to-messages/

**Comment by Asgaros** [comment]
@Igor-Yworld

Finally and after a lot of code-refactoring I could implement this. I would be happy if you could have a short look over the latest development-version and give me feedback on this.

The creation of topics/posts happens now at the same page. The same behavior is for quoting, which means: You can now quote multiple posts at once and everytime the quote will be insert to the editor automatically.

The logic for this was a little bit complex so some testing would be nice to ensure that everything is working fine in a different environment as well, so I can release it as soon as possible. :)

**Comment by Igor-Yworld** [comment]
@Asgaros Thank you very much, tremendous work!
Everything works perfectly.
