### ISSUE TITLE
Thread button modifications

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#56]
Make some changes to thread-buttons.

See:
http://i.imgur.com/fISpT1A.png
https://wordpress.org/support/topic/minor-glitches?replies=12

**Comment by Numeriku** [comment]
this is a good suggestion, i'm not sure if this will be too hard to implement, i mean it doesn't look nice having 2 rows of the same button.

**Comment by Asgaros** [comment]
This has been changed here:
https://github.com/Asgaros/asgaros-forum/commit/03b67483f9d7b1ddbe35f52cd23a4f45bceabb42
