### ISSUE TITLE
Refactor wpdb querys, to utilize wordpress to its fullest

### ISSUE THREAD

**Issue by Hammster** [Asgaros/asgaros-forum#57]
nearly all $wpdb->query( $wpdb->prepare ( ... ) ) can be refactor to use 

- $wpdb->insert
- $wpdb->update
- $wpdb->delete

The reason behind $wpdb->query is that it is **only** used [if the querys get to complex to be used by the wordpress sql wrapper](https://codex.wordpress.org/Class_Reference/wpdb#Running_General_Queries). 

Also it makes the code more accessible and better formatted.

Cheers and thank you for making this plugin :+1:

**Comment by Asgaros** [comment]
Hey Hammster!

Thats a good point. I will check those querys and change them. :+1:
