### ISSUE TITLE
Need images

### ISSUE THREAD

**Issue by savelyevartem** [Asgaros/asgaros-forum#61]
Need images for forums and categories!  And it will be a masterpiece . Thank you!

**Comment by Asgaros** [comment]
Hello savelyevartem,

where do you want to have images? There are already icons in the frontend for forums and threads. Maybe they are not shown correctly?

**Comment by savelyevartem** [comment]
Replace icons, downloadable images from the forum settings

**Comment by Asgaros** [comment]
Hello @savelyevartem 

In this commit (https://github.com/Asgaros/asgaros-forum/commit/373bd1e820cde4da16a749f6167865c6fd0deaee) I added an ID for forums to the overview. This allows you to set own CSS styling rules to your forums.

You can find an example on this page in the post number 3:
https://wordpress.org/support/topic/inserting-images-future-suggestions?replies=4

Maybe this will be helpful.
