### ISSUE TITLE
Old threads don't appear anymore.

### ISSUE THREAD

**Issue by chesu** [Asgaros/asgaros-forum#65]
Hello.I'm having problems with some old posts that just don't appear anymore. if i go to the recent posts i can see and click them,but i can't find them in the forum anymore.Can you help?

**Comment by Asgaros** [comment]
I think they should be on other pages. Have you checked the pages-navigation?

**Comment by Asgaros** [comment]
http://fs5.directupload.net/images/160323/d4f6paak.png

**Comment by chesu** [comment]
![capture](https://cloud.githubusercontent.com/assets/18039776/14010822/56bc83c6-f1a1-11e5-9a74-466e5acc6346.JPG)
![capture2](https://cloud.githubusercontent.com/assets/18039776/14010821/56bc361e-f1a1-11e5-8da5-b0040d79738a.JPG)
no.it's not on other pages.

**Comment by chesu** [comment]
is there a way i can manage the threads?

**Comment by Asgaros** [comment]
Do you have a link for me where I can see this problem in action?

Do you have some steps to reproduce it?

Have you tried to disable your other WordPress plugins? Maybe it is a caching issue.

**Comment by Asgaros** [comment]
Any new information about this, @chesu ?

If not I will close this ticket.
