### ISSUE TITLE
Signatures

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#69]
Reference:
https://wordpress.org/support/topic/inserting-images-future-suggestions?replies=1
https://wordpress.org/support/topic/what-i-would-like-this-plugin?replies=1

**Comment by Asgaros** [comment]
I decided to not implement signatures into the forums because I think that it can distract people from the content of a topic/post. Members can also abuse signatures for spam or other kind of things so it can result to much more work for administrators.

If users want to show additional information they can use some other WordPress plugins to extend the profiles of users and integrate that kind of information via hooks into the forum.

I added a hook to the forum called asgarosforum_after_post_message which can be used to add information at the end of a post.

**Comment by Asgaros** [comment]
Because it got requested many times I will implement this feature. It will be disabled by default but can be activated. Only text will be allowed in signatures because images and HTML can distract users too much.

**Comment by Elwoodb** [comment]
Hello, congratulations for working on this forum.
I am disappointed by the fact that I can not add an image to the signature.
I understand your argument that it distracts the members.
but would not it make sense to let each administrator to decide?
Providing the possibility of putting an image in signature is usual in a large majority of forums ...
If it is not be important to you but it can be for the other;)
In the hope that you will come back on your decision.
Respectfully,

Elwoodb.
Sorry for my English I use google translation

**Comment by Savaena** [comment]
I agreed with Elbwoodb. The users of our organization have been asking to be able to have images in their signature. We like using your forums but find this lack of feature a real sore point to the extent we are looking into other alternatives for our forums.

**Comment by Asgaros** [comment]
Hello @Savaena 

It is already possible to add images via HTML to your signature. You just have to activate the "Allow HTML in sigatures" option in Forum -> Settings -> Signatures
