### ISSUE TITLE
Theme manager

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#70]
Add a theme manager to the plugin so administrators can override/change/add a theme for their forum which will look better in a custom WordPress theme.

Initial work is done by @Hisol in this pull request: https://github.com/Asgaros/asgaros-forum/pull/67

**Comment by Asgaros** [comment]
Okay @Hisol, lets assume that someone has created a custom theme for the forum. If so, I think it makes no sense to provide the color picker for it because someone who can create a custom theme can also change the color to a desired value. So maybe we should just hide it when a theme other than the default one is used?

**Comment by Hisol** [comment]
I agree, what I am pondering is for a theme to have the ability to have dynamic configuration components (like the colour picker) which can be added by the theme's author.  So in the case of the default theme it would have the colour picker, and it would be visible.  Other themes would be able to have custom code if they wanted, and that would appear according to the selected theme.

So, as you say, when selecting anything other than the default theme the colour picker will not appear, but selecting a theme with a custom modifier will inject the appropriate elements into the forum and the options page.

I think I have an idea of how I'd like to code this up and can get stuck into it when I get a minute?

**Comment by Asgaros** [comment]
I think we should not implement some configuration files for themes now. It will be a little bit too much and we should keep it simple. The color picker is only a tool for changing the color easy. If someone can build his own theme, he can change it by himself too.

I added a check to the options page and will add some JavaScript logic for it later.

**Comment by Asgaros** [comment]
Okay, some more things I want to change ...

First, beside of the Theme Manager: We have a color-picker for the background color and the problem is, that the text is not viewable when a certain color is selected (white background, white text for example). So I should add a color-picker for the text of the default theme as well so both things can be adjusted.

This affects the Theme Manager in some way: We dont need a dark-theme-example when all of the colors of the default theme can be changed easily from the administration area. So I think we should remove it.

Also there is another good reason to remove that dark-theme-example: It gets copied to the external custom-themes-directory. When we have to fix some CSS in the dark-theme-example, we cant just override it in the custom-themes-directory because it should be a safe place for own modifications. That means people may wondering why a CSS bug has been fixed and it is still not looking well they are using the dark-theme-example. Why? Because they are using an old-version of the dark-theme-example which is in their custom-themes-directory and not the up-to-date one in the plugin-directory.

Conclusion: Only one default-theme which can be changed easily with color-pickers. Hide the Theme Manager dropdown when there are no custom-themes but create a themes-asgarosforum directory for custom themes. When there are custom themes in this directory, show the Theme Manager dropdown. If someone is using a theme other than the default one, hide all color-pickers.

I think this will be the best way because we only have to take care of one default-theme and it will not confuse the user because they are using some old CSS so we dont have to care at all about the CSS files in the custom-themes directory.

I hope you are fine with it! :)

**Comment by Asgaros** [comment]
I changed another thing: Now each theme must have a mobile.css and widgets.css file too. Those files should be included to encourage theme-authors for providing the best design-results for every aspect of the plugin. But the files can be empty too if they dont need them.
