### ISSUE TITLE
membre space

### ISSUE THREAD

**Issue by beyen** [Asgaros/asgaros-forum#77]
hi ! evrybody , how create membre space with android

**Comment by Asgaros** [comment]
Hello @beyen 

What do you mean with member-space?

**Comment by beyen** [comment]
Member area of application of association of young researchers

**Comment by Asgaros** [comment]
I dont really get what you want to do. Is this a feature request for the forum? Can you explain it a little bit more detailled? Or is it a general question because something is not working?

**Comment by beyen** [comment]
I wanna to develope a mobile application with android for users.The users must register or login, manage their profil, reseive notification form the admin about thier acception in the application also they can propose some question on the forum.
 I hope you undrestand my problem.

**Comment by beyen** [comment]
I wanna to develope a mobile application with android for users.The users must register or login, manage their profil, reseive notification form the admin about thier acception in the application also they can propose some question on the forum.
 I hope you undrestand my problem.

**Comment by Asgaros** [comment]
I am not really sure what you mean.

Have you found a bug which is preventing you from creating such an application?

Do you need something special so you want to make a feature request?
