### ISSUE TITLE
Avatarka widgets

### ISSUE THREAD

**Issue by ironboys** [Asgaros/asgaros-forum#78]
Hello. Here I on the website http://ironboy.ru have drawn an avatar conclusion in a widget of the last subjects, but it has turned out so to be removed an avatar of the last user in a subject. How to make that the avatar of the author of a subject was removed

**Comment by Asgaros** [comment]
Hello!

For me everything is looking correct. The Widget is showing information of the user of the last post in a subject so it also shows the avatar of the user who made the last post in a topic. Or is there a misunderstanding?

**Comment by ironboys** [comment]
As on me has to show an avatar of the author of a subject, also so in all forums it is displayed a nickname and an avatar of the author of a subject and is below written who the last has written the answer

**Comment by Asgaros** [comment]
I dont know whats wrong. The widget is used for showing information about the "last posts" in the forum so it is showing user-information of the user who made that last post. Correct, right? It is not a "last topic"-widget.
