### ISSUE TITLE
Response No visible

### ISSUE THREAD

**Issue by TheFostersFr** [Asgaros/asgaros-forum#80]
Hi,

I'm french so .. ^^

When a member reply to a subject, he can't view his message. He need to logout and login to view his message.
Same error for everyone, please help ?

http://thefosters.fr/forum

Thanks :)

**Comment by Asgaros** [comment]
Hello!

It seems that you are using some kind of caching plugin, right? Can you please try to deactivate it for the forum page?

**Comment by TheFostersFr** [comment]
Hi !

Thanks so much ! In fact my plugin WP SUPER CACHE was the problem ... I can't select url to desactivate so i desactivate all and i will search to another plugin cache ...

Thanks so much !!!

**Comment by TheFostersFr** [comment]
P.S : can you add the possibility to add shortcodes in the forum message ?
Thanks.
