### ISSUE TITLE
problem with widget

### ISSUE THREAD

**Issue by appsfinder** [Asgaros/asgaros-forum#82]
the widget post link not working for me? 

i get this http://www.mysite.com/?view=thread&id=1#postid-1

my page is called forum its missing from the link
 e:g http://www.mysite.com/forum/?view=thread&id=1#postid-1

please can you help me

**Comment by Asgaros** [comment]
Hey,

pleasy configure your widget correctly. You have to select the page at it where your forum is located. After it the links should be working correctly. :)
