### ISSUE TITLE
Notification text needs reformatting

### ISSUE THREAD

**Issue by KTS915** [Asgaros/asgaros-forum#84]
I opened a support thread about this here: https://wordpress.org/support/topic/notification-text-needs-reformatting?replies=1

In case it's easier to put the suggested solutions here, here they are. For the notification to subscribers, I suggest this:
```
$notification_message = sprintf(__('Hello,

you got this mail because there is a new answer in a forum-topic you have subscribed to:
%s

Answer:
%s

Link to the new answer:
%s

You can unsubscribe from this topic using the unsubscribe-link at the end of the topic as a logged-in user. Please dont answer to this mail!', 'asgaros-forum'), $thread_name, $answer_text, $answer_link);
```

For the notification to admins, I suggest this:
```
$notification_message = sprintf(__('Hello,

you got this mail because there is a new forum-topic:
%s

Text:
%s

Link to the new topic:
%s', 'asgaros-forum'), $topic_name, $topic_text, $topic_link);
```

**Comment by Asgaros** [comment]
@KTS915 Are you sure that your translation files contains the translations for the mail-messages? I tested it with my old solution and mail-notifications got sent correctly translated.

**Comment by KTS915** [comment]
@Asgaros: I am not actually translating these  messages, so the translation files don't matter to me. 

What I am doing is re-writing the messages in English in a style that suits my site better, and for that I use the [Say What?](https://wordpress.org/plugins/say-what/) plugin, which needs the format to be as explained here: https://codex.wordpress.org/I18n_for_WordPress_Developers and http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/

**Comment by Asgaros** [comment]
Okay, I will change it as suggested. :+1:

**Comment by KTS915** [comment]
Thank you!

**Comment by Asgaros** [comment]
I changed the strings into the single-quote format in this commit: https://github.com/Asgaros/asgaros-forum/commit/b80f633588f6194b79ce98774d0921755c7d7705

Also I use HTML-tags for line-breaks now because it makes sense to send out mails in the HTML-format because HTML is used when users use the formatting-options inside the editor.

Can you please check if its working with those changes?

**Comment by KTS915** [comment]
Yes, it's working for me. Thanks again!
