### ISSUE TITLE
yellow background on: Sorry, only logged in users have access to the forum. » Login

### ISSUE THREAD

**Issue by kilimats** [Asgaros/asgaros-forum#86]
how do i change the yellow background on this message: Sorry, only logged in users have access to the forum. » Login

My text is set to white and become invisible on yellow background when that message appears

**Comment by Asgaros** [comment]
Hello @kilimats 

You can change the color of the background via CSS in your themes CSS file. Here is an example:
```
#af-wrapper .error {
    background-color: red;
}
```
