### ISSUE TITLE
Iamges

### ISSUE THREAD

**Issue by gmfa55** [Asgaros/asgaros-forum#94]
Hi all 
I have just installed the asgaros-forum on my website and it works a treat thanks.
Just wanted to ask a question, when i post images the image dose not sow on the thread or post?
I thought that on all forums the pictures posted do show as a thumbnail is this possible?

Thanks
Francis

**Comment by Asgaros** [comment]
Hello, you can insert images via the editor. Click on the little image-button and paste the image-url into it.

**Comment by gmfa55** [comment]
I can upload them but we cannot see a thumb nail image on the post/thread

Hope you understand what i mean

Thanks for your fast reply

**Comment by Asgaros** [comment]
Yes, you upload them so they appear in the file-list like every other file (zip-archives for example). When you want to include it somewhere you can copy the URL of the uploaded image and insert it into your post via the image-button in your editor.

**Comment by gmfa55** [comment]
Hi all
What mean is when you upload a picture to the threat it will only show the hyper link, not a thumb nail image.
i have attached a screen shot of a forum where i do my postings.
can it be done like this one?
  
![forum test1](https://cloud.githubusercontent.com/assets/21281561/18045904/8425fab2-6dd5-11e6-87d9-f65cdad67d88.jpg)

**Comment by gmfa55** [comment]
Hi again
Here you have how our forum page looks when we upload the picture, as you can see you cannot se the thumbnail on the post, only the hyperlink.
![forum test2](https://cloud.githubusercontent.com/assets/21281561/18046016/1c411b74-6dd6-11e6-9bfc-67b493d7f873.jpg)

Thanks
Francis

**Comment by Asgaros** [comment]
Yes, it is on purpose because the upload-form is intended for "files" like zip-archives and other stuff.

Please use the editor if you want to insert one of the pictures into your posts:
![screenshot 3](https://cloud.githubusercontent.com/assets/12525671/18046705/654c9a7a-6dd9-11e6-8abd-640a58f4e328.png)

**Comment by gmfa55** [comment]
Thanks for your help

Francis

check out our website gmfa.bmfa.org
