### ISSUE TITLE
forum when opening posts etc

### ISSUE THREAD

**Issue by topdog1965** [Asgaros/asgaros-forum#96]
the forum shows fine but when opening the forum it seems to jump to the top of the page and you have to keep scrolling down the page to open another post or respond etc it is not fixed.

thankyou

**Comment by Asgaros** [comment]
Hello @topdog1965 ,

can you please explain the problem a little bit more detailled because I am not exactly sure whats wrong. Can it be possible that it is a problem with your used theme?
