### ISSUE TITLE
Thumbnails for uploads

### ISSUE THREAD

**Issue by Asgaros** [Asgaros/asgaros-forum#97]
Add thumbnails for uploads. Create thumbnail files or just show a resized version? Keep in mind that the last solution has a big impact on mobile connections.

References:
https://wordpress.org/support/topic/display-image-uploads/
https://wordpress.org/support/topic/thumbnail-image-14/

**Comment by DilShahDirar** [comment]
Urgently need this option. I cannot continue without this. Stuck on my project :p
Add it asap id you can
