### ISSUE TITLE
Read topics not working on 1.2.6

### ISSUE THREAD

**Issue by jangevaare** [Asgaros/asgaros-forum#99]
I had to rollback to 1.2.5 because marking as read would no longer work in 1.2.6, nor would the read status of a topic update after visiting it.

Thanks for your continued hard work!

**Comment by Asgaros** [comment]
Hello @jangevaare 

Thank you for the bug-report. I could reproduce it and will try to fix it as soon as possible!

**Comment by Asgaros** [comment]
And its fixed! I will release a new update in the next 24 hours.

Thanks again! :)
